;
; Copyright (c) MPC Data Limited 2007. All Rights Reserved.
;
;------------------------------------------------------------------------------
;
;  Header:  am3x_mcasp.inc
;
;  This header file is comprised of component header files that define
;  the register layout of each System on Chip (SoC) component.

;------------------------------------------------------------------------------

AM3X_MCASP_PID_OFFSET         EQU 0x0000
AM3X_MCASP_PWRDEMU            EQU 0x0004
AM3X_MCASP_PFUNC_OFFSET       EQU 0x0010
AM3X_MCASP_PDIR_OFFSET        EQU 0x0014
AM3X_MCASP_PDOUT_OFFSET       EQU 0x0018
AM3X_MCASP_PDIN_PDSET_OFFSET  EQU 0x001C
AM3X_MCASP_PDIN_OFFSET        EQU 0x001C
AM3X_MCASP_PDSET_OFFSET       EQU 0x001C
AM3X_MCASP_PDCLR_OFFSET       EQU 0x0020

    END
