//
//  File:  em9170.c
//
//  do some initialization for EM9170.
//
//-----------------------------------------------------------------------------
#include "bsp.h"
#pragma warning(push)
#pragma warning(disable: 4115)
#include <fmd.h>
#pragma warning(pop)
//#include "loader.h"
#include "common_types.h"			//CS&ZHL MAY-5-2011: supporting splash screen


//-----------------------------------------------------------------------------
// External Functions

//-----------------------------------------------------------------------------
//! \brief		void EM9170_IOConfig()
//! function:	(1) config UART3 RXD and TXD pins
//					(2) config all GPIO pins in EM9170 in input state
//-----------------------------------------------------------------------------
BOOL EM9170_IOConfig(void)
{
    PCSP_IOMUX_REGS		pIOMUX;
	PCSP_GPIO_REGS			pGPIO1;
	PCSP_GPIO_REGS			pGPIO2;
	PCSP_GPIO_REGS			pGPIO3;
	PCSP_GPIO_REGS			pGPIO4;

    pIOMUX = (PCSP_IOMUX_REGS) OALPAtoUA(CSP_BASE_REG_PA_IOMUXC);
    if (pIOMUX == NULL)
    {
        OALMSG(TRUE, (L"EM9170 GPIO Config: IOMUXC mapping failed!\r\n"));
        return FALSE;
    }

	pGPIO1 = (PCSP_GPIO_REGS)OALPAtoUA(CSP_BASE_REG_PA_GPIO1);
    if (pGPIO1 == NULL)
    {
        OALMSG(TRUE, (L"EM9170 GPIO Config: GPIO1 mapping failed!\r\n"));
        return FALSE;
    }
	pGPIO2 = (PCSP_GPIO_REGS)OALPAtoUA(CSP_BASE_REG_PA_GPIO2);
    if (pGPIO2 == NULL)
    {
        OALMSG(TRUE, (L"EM9170 GPIO Config: GPIO2 mapping failed!\r\n"));
        return FALSE;
    }
	pGPIO3 = (PCSP_GPIO_REGS)OALPAtoUA(CSP_BASE_REG_PA_GPIO3);
    if (pGPIO3 == NULL)
    {
        OALMSG(TRUE, (L"EM9170 GPIO Config: GPIO3 mapping failed!\r\n"));
        return FALSE;
    }
	pGPIO4 = (PCSP_GPIO_REGS)OALPAtoUA(CSP_BASE_REG_PA_GPIO4);
    if (pGPIO4 == NULL)
    {
        OALMSG(TRUE, (L"EM9170 GPIO Config: GPIO4 mapping failed!\r\n"));
        return FALSE;
    }

    KITLOutputDebugString("->EM9170_IOConfig\r\n");

	// UART3.RXD
 /*   OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSPI1_MOSI, DDK_IOMUX_PIN_MUXMODE_ALT2, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSPI1_MOSI, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
										DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, 
										DDK_IOMUX_PAD_HYSTERESIS_DISABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
	OAL_IOMUX_SET_INPUT(pIOMUX, DDK_IOMUX_SELEIN_UART3_IPP_UART_RXD_MUX, 0);			// 0 -> CSPI1_MOSI for Mode: ALT2

	// UART3.TXD
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSPI1_MISO, DDK_IOMUX_PIN_MUXMODE_ALT2, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSPI1_MISO, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
										DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, 
										DDK_IOMUX_PAD_HYSTERESIS_DISABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
*/
	KITLOutputDebugString("CS&ZHL Jun 09-2011: Set EM9160 GPIO as input\r\n" );

    // - GPIO0
    // - Function ALT 5 on CSPI1_MISO pio: gpio1_15
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSPI1_MISO, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSPI1_MISO, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
	// Set GPIO1_15 Direction as Input
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<15)));

    // - GPIO1
    // - Function ALT 5 on CSPI1_MOSI pio: gpio1_14
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSPI1_MOSI, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSPI1_MOSI, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
	// Set GPIO1_14 Direction as Input
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<14)));

	// - GPIO2
    // - Function ALT 5 on CSI_D4 pio: gpio1_29
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_D4, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_D4, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
	// Set GPIO1_29 Direction as Input
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<29)));

	// - GPIO3
    // - Function ALT 5 on CSI_D2 pio: gpio1_29
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_D2, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_D2, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<27)));

	// - GPIO4
    // - Function ALT 5 on CSI_D6 pio: gpio1_31
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_D6, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_D6, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<31)));

	// - GPIO5
    // - Function ALT 5 on CSI_D3 pio: gpio1_28
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_D3, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_D3, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<28)));

	// - GPIO6
    // - Function ALT 5 on I2C1_CLK pio: gpio1_12
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_I2C1_CLK, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_I2C1_CLK, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<12)));

	// - GPIO7
    // - Function ALT 5 on I2C1_DAT pio: gpio1_13
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_I2C1_DAT, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_I2C1_DAT, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<13)));

	// - GPIO8
    // - Function ALT 5 on CSI_D5 pio: gpio1_30
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_D5, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_D5, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<30)));

	// - GPIO9
    // - Function ALT 5 on CSI_D7 pio: gpio1_6
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_D7, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_D7, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<6)));

	// - GPIO10
    // - Function ALT 5 on GPIO_F pio: gpio1_5
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_GPIO_F, DDK_IOMUX_PIN_MUXMODE_ALT0, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_GPIO_F, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<5)));

	// - GPIO11
    // - Function ALT 5 on CSPI1_RDY pio: gpio2_22
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSPI1_RDY, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSPI1_RDY, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO2->GDIR, (INREG32(&pGPIO2->GDIR) & ~(0x1<<22)));

	// - GPIO12
    // - Function ALT 5 on CSPI1_SS1 pio: gpio1_17
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSPI1_SS1, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSPI1_SS1, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<17)));

	// - GPIO13
    // - Function ALT 5 on CSPI1_SS0 pio: gpio1_16
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSPI1_SS0, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSPI1_SS0, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<16)));

	// - GPIO14
    // - Function ALT 5 on UART1_RTS pio: gpio4_24
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_UART1_RTS, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_UART1_RTS, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO4->GDIR, (INREG32(&pGPIO4->GDIR) & ~(0x1<<24)));

	// - GPIO15
    // - Function ALT 5 on CSI_VSYNC pio: gpio1_9
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_VSYNC, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_VSYNC, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<9)));

	// - GPIO16
    // - Function ALT 5 on D13 pio: gpio4_7
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_D13, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_D13, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO4->GDIR, (INREG32(&pGPIO4->GDIR) & ~(0x1<<7)));

	// - GPIO17
    // - Function ALT 5 on D12 pio: gpio4_8
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_D12, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_D12, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO4->GDIR, (INREG32(&pGPIO4->GDIR) & ~(0x1<<8)));

	// - GPIO18
    // - Function ALT 5 on D9 pio: gpio4_11
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_D9, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_D9, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO4->GDIR, (INREG32(&pGPIO4->GDIR) & ~(0x1<<11)));

	// - GPIO19
    // - Function ALT 5 on D8 pio: gpio4_12
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_D8, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_D8, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO4->GDIR, (INREG32(&pGPIO4->GDIR) & ~(0x1<<12)));

	// - GPIO20
    // - Function ALT 5 on UPLL_BYPCLK pio: gpio3_16
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_UPLL_BYPCLK, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OUTREG32 (&pGPIO3->GDIR, (INREG32(&pGPIO3->GDIR) & ~(0x1<<16)));

	// - GPIO21
    // - Function ALT 5 on VSTBY_REQ pio: gpio3_17
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_VSTBY_REQ, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_VSTBY_REQ, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO3->GDIR, (INREG32(&pGPIO3->GDIR) & ~(0x1<<17)));

	// - GPIO22
    // - Function ALT 5 on VSTBY_ACK pio: gpio3_18
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_VSTBY_ACK, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_VSTBY_ACK, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO3->GDIR, (INREG32(&pGPIO3->GDIR) & ~(0x1<<18)));

	// - GPIO23
    // - Function ALT 5 on POWER_FAIL pio: gpio3_19
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_POWER_FAIL, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_POWER_FAIL, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO3->GDIR, (INREG32(&pGPIO3->GDIR) & ~(0x1<<19)));

	// - GPIO24
    // - Function ALT 5 on CSI_MCLK pio: gpio1_8
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_MCLK, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_MCLK, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<8)));

	// - GPIO25
    // - Function ALT 5 on CSI_PIXCLK pio: gpio1_11
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_PIXCLK, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_PIXCLK, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<11)));

	// - GPIO26
    // - Function ALT 5 on CSI_HSYNC pio: gpio1_10
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CSI_HSYNC, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CSI_HSYNC, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<10)));

	// - GPIO27
    // - Function ALT 5 on CLKO pio: gpio2_21
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CLKO, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CLKO, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO2->GDIR, (INREG32(&pGPIO2->GDIR) & ~(0x1<<21)));

	// - GPIO28
    // - Function ALT 5 on RTCK pio: gpio3_14
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_RTCK, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_RTCK, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO3->GDIR, (INREG32(&pGPIO3->GDIR) & ~(0x1<<14)));

	// - GPIO29
    // - Function ALT 5 on EXT_ARMCLK pio: gpio3_15
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_EXT_ARMCLK, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OUTREG32 (&pGPIO3->GDIR, (INREG32(&pGPIO3->GDIR) & ~(0x1<<15)));

	// - GPIO30 (CAN1_TX)
    // - Function ALT0 on GPIO_A pio: gpio1_0
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_GPIO_A, DDK_IOMUX_PIN_MUXMODE_ALT0, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_GPIO_A, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<0)));

	// - GPIO31 (CAN2_TX)
    // - Function ALT 0 on  GPIO_C pio: gpio1_2
    // - PIO pull-up-100K
    // - PIO on VDD(3v3)
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_GPIO_C, DDK_IOMUX_PIN_MUXMODE_ALT5, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_GPIO_C, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
                                     DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, DDK_IOMUX_PAD_HYSTERESIS_ENABLE, DDK_IOMUX_PAD_VOLTAGE_3V3);
    OUTREG32 (&pGPIO1->GDIR, (INREG32(&pGPIO1->GDIR) & ~(0x1<<2)));

	return TRUE;
}


//-----------------------------------------------------------------------------
//! \brief		void EM9170_ISABusSetup()
//! function:	(1) config ISA Bus related pins
//					(2) setup CS5_ bus timing
//					(3) dump Board Info stored in CPLD 
//-----------------------------------------------------------------------------
BOOL EM9170_ISABusSetup(void)
{
    PCSP_IOMUX_REGS	pIOMUX;
	PCSP_WEIM_REGS	pWEIM;
	PEM9K_CPLD_REGS	pCPLD;
	UCHAR						VID[5];		
	DWORD						i;

    KITLOutputDebugString("->EM9170_ISABusSetup\r\n");

    pIOMUX = (PCSP_IOMUX_REGS) OALPAtoUA(CSP_BASE_REG_PA_IOMUXC);
    if (pIOMUX == NULL)
    {
		KITLOutputDebugString("EM9170_ISABusSetup: IOMUXC mapping failed!\r\n");
        return FALSE;
    }

    pWEIM = (PCSP_WEIM_REGS) OALPAtoUA(CSP_BASE_REG_PA_WEIM);
    if (pWEIM == NULL)
    {
		KITLOutputDebugString("EM9170_ISABusSetup: WEIM mapping failed!\r\n");
        return FALSE;
    }

	pCPLD = (PEM9K_CPLD_REGS)OALPAtoUA(CSP_BASE_MEM_PA_CS5);
    if (pCPLD == NULL)
    {
		KITLOutputDebugString("EM9170_ISABusSetup: CS5 mapping failed!\r\n");
        return FALSE;
    }

	KITLOutputDebugString("EM9170_ISABusSetup: config pins for ISA bus\r\n");
	// setup EB0# to CPLD and ISA
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_EB0, DDK_IOMUX_PIN_MUXMODE_ALT0, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_EB0, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
										DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, 
										DDK_IOMUX_PAD_HYSTERESIS_DISABLE, DDK_IOMUX_PAD_VOLTAGE_1V8);

	// setup RW# to CPLD and ISA
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_RW, DDK_IOMUX_PIN_MUXMODE_ALT0, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_RW, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
										DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, 
										DDK_IOMUX_PAD_HYSTERESIS_DISABLE, DDK_IOMUX_PAD_VOLTAGE_1V8);

	// setup OE# to CPLD and ISA
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_OE, DDK_IOMUX_PIN_MUXMODE_ALT0, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_OE, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
										DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, 
										DDK_IOMUX_PAD_HYSTERESIS_DISABLE, DDK_IOMUX_PAD_VOLTAGE_1V8);

	// setup CS5# to CPLD and ISA
    OAL_IOMUX_SET_MUX(pIOMUX, DDK_IOMUX_PIN_CS5, DDK_IOMUX_PIN_MUXMODE_ALT0, DDK_IOMUX_PIN_SION_REGULAR);
    OAL_IOMUX_SET_PAD(pIOMUX, DDK_IOMUX_PAD_CS5, DDK_IOMUX_PAD_SLEW_FAST, DDK_IOMUX_PAD_DRIVE_NORMAL, 
										DDK_IOMUX_PAD_OPENDRAIN_DISABLE, DDK_IOMUX_PAD_PULL_UP_100K, 
										DDK_IOMUX_PAD_HYSTERESIS_DISABLE, DDK_IOMUX_PAD_VOLTAGE_1V8);

	KITLOutputDebugString("EM9170_ISABusSetup: Setup CS5 Bus Timing\r\n");
	// ISA Bus cycle = 300ns, read/write width = 240ns
    OUTREG32 (&pWEIM->CSCR5U, 0x00006804);
    OUTREG32 (&pWEIM->CSCR5L, 0x66668b61);
	KITLOutputDebugString("CSCR5U = 0x%x, CSCR5L = 0x%x\r\n", INREG32(&pWEIM->CSCR5U), INREG32(&pWEIM->CSCR5L));

	KITLOutputDebugString("pCPLD->TypeReg = 0x%x\r\n", (DWORD)INREG8(&pCPLD->TypeReg));
	VID[0] = INREG8(&pCPLD->VID[3]);		// OFFSET = 0x58, Vendor ID = "em9k"	
	VID[1] = INREG8(&pCPLD->VID[2]);
	VID[2] = INREG8(&pCPLD->VID[1]);
	VID[3] = INREG8(&pCPLD->VID[0]);
	VID[4] = '\0';
	KITLOutputDebugString("EM9170_ISABusSetup: EM9170 VID = %s\r\n", VID);

	KITLOutputDebugString("EM9170_ISABusSetup: pCPLD->StateReg = 0x%x\r\n", (DWORD)INREG8(&pCPLD->StateReg));
    OUTREG8(&pCPLD->ResetReg, 0);			// clear CPU_EN flag
    OUTREG8(&pCPLD->ISACtrlReg, 0);			// disable ISA operations
	OUTREG8(&pCPLD->PwrBtnReg, 0);			// disable Power Button
	OUTREG8(&pCPLD->PWMCtrlReg, 0);		// disable PWM1 ouput
	// check is DBGSL# is short
	for(i = 0; i < 5; i++)
	{
		if(!(INREG8(&pCPLD->StateReg) & EM9K_CPLD_STATE_DBGSL))
		{
			break;
		}
	}
	if( i < 5 )
	{
		OUTREG8 (&pCPLD->PwrBtnReg, EM9K_CPLD_PWRBTN_EN);			// enable Power Button
	}
    OUTREG8 (&pCPLD->ResetReg, 0x55);		// set CPU_EN flag
	KITLOutputDebugString("EM9170_ISABusSetup: pCPLD->StateReg = 0x%x\r\n", (DWORD)INREG8(&pCPLD->StateReg));

	return TRUE;
}

