;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this sample source code is subject to the terms of the Microsoft
; license agreement under which you licensed this sample source code. If
; you did not accept the terms of the license agreement, you are not
; authorized to use this sample source code. For the terms of the license,
; please see the license agreement between you and Microsoft or, if applicable,
; see the LICENSE.RTF on your install media or the root of your tools installation.
; THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
;
;------------------------------------------------------------------------------
;
;  File:  omap5912_ocpi.inc
;
;  This file defines offset addresses for OCPI registers.
;
OMAP5912_OCPI_ADDRFAULT_REGS_OA         EQU     0x0000
OMAP5912_OCPI_MCMDFAULT_REGS_OA         EQU     0x0004
OMAP5912_OCPI_SINTERRUPT0_REGS_OA       EQU     0x0008
OMAP5912_OCPI_ABORTTYPE_REGS_OA         EQU     0x000C
OMAP5912_OCPI_SINTERRUPT1_REGS_OA       EQU     0x0010
OMAP5912_OCPI_PROTECT_REGS_OA           EQU     0x0014
OMAP5912_OCPI_SECURE_REGS_OA            EQU     0x0018

;------------------------------------------------------------------------------

                                        END
