;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this sample source code is subject to the terms of the Microsoft
; license agreement under which you licensed this sample source code. If
; you did not accept the terms of the license agreement, you are not
; authorized to use this sample source code. For the terms of the license,
; please see the license agreement between you and Microsoft or, if applicable,
; see the LICENSE.RTF on your install media or the root of your tools installation.
; THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
;
;------------------------------------------------------------------------------
;
;  File:  omap5912_ulpd.inc
;
;  This file contains offset addresses for ULPD registers.
;

OMAP5912_ULPD_COUNTER_32_LSB                    EQU     0x0000
OMAP5912_ULPD_COUNTER_32_MSB                    EQU     0x0004
OMAP5912_ULPD_COUNTER_HIGH_FREQ_LSB             EQU     0x0008
OMAP5912_ULPD_COUNTER_HIGH_FREQ_MSB             EQU     0x000C
OMAP5912_ULPD_GAUGING_CTRL                      EQU     0x0010
OMAP5912_ULPD_IT_STATUS                         EQU     0x0014
OMAP5912_ULPD_SLICER_SETUP                      EQU     0x0024
OMAP5912_ULPD_VTCXO_SETUP                       EQU     0x0028
OMAP5912_ULPD_RF_SETUP                          EQU     0x002C
OMAP5912_ULPD_CLOCK_CTRL                        EQU     0x0030
OMAP5912_ULPD_SOFT_REQ                          EQU     0x0034
OMAP5912_ULPD_COUNTER_32_FIQ                    EQU     0x0038
OMAP5912_ULPD_STATUS_REQ                        EQU     0x0040
OMAP5912_ULPD_PLL_DIV                           EQU     0x0044
OMAP5912_ULPD_PLL_CTRL_STATUS                   EQU     0x004C
OMAP5912_ULPD_POWER_CTRL                        EQU     0x0050
OMAP5912_ULPD_STATUS_REQ2                       EQU     0x0054
OMAP5912_ULPD_SLEEP_STATUS                      EQU     0x0058
OMAP5912_ULPD_SOFT_DISABLE_REQ                  EQU     0x0068
OMAP5912_ULPD_RESET_STATUS                      EQU     0x006C
OMAP5912_ULPD_REVISION_NUMBER                   EQU     0x0070
OMAP5912_ULPD_MCBSP2_CLK_DIV_CTRL_SEL           EQU     0x0074
OMAP5912_ULPD_MCBSP1_CLK_DIV_CTRL_SEL           EQU     0x0078
OMAP5912_ULPD_CAM_CLK_CTRL                      EQU     0x007C
OMAP5912_ULPD_SOFT_REQ_REG2                     EQU     0x0080

;------------------------------------------------------------------------------

                                                END

