//------------------------------------------------------------------------------
//
//  File:  bsp_dirvers.h
//
//------------------------------------------------------------------------------
#ifndef __BSP_DRIVERS_H
#define __BSP_DRIVERS_H


//
// GPIO IO Control Codes
//
#define GPIO_IOCTL_OUT_ENABLE			CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 3900, METHOD_BUFFERED, FILE_ANY_ACCESS)  
#define GPIO_IOCTL_OUT_DISABLE			CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 3901, METHOD_BUFFERED, FILE_ANY_ACCESS)  
#define GPIO_IOCTL_OUT_SET				CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 3902, METHOD_BUFFERED, FILE_ANY_ACCESS)  
#define GPIO_IOCTL_OUT_CLEAR			CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 3903, METHOD_BUFFERED, FILE_ANY_ACCESS)  
#define GPIO_IOCTL_PIN_STATE			CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 3904, METHOD_BUFFERED, FILE_ANY_ACCESS)  

//
// CS&ZHL JLY-1-2011: create unique system I/O control codes (IOCTL) for ISA_IRQ
//
#define IOCTL_WAIT_FOR_IRQ				CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 3920, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SEND_EOI					CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 3921, METHOD_BUFFERED, FILE_ANY_ACCESS)

//
// CS&ZHL JUN-24-2011: cmd code for KernelIoControl
//
#define IOCTL_HAL_BOARDINFO_READ		CTL_CODE(FILE_DEVICE_HAL, 4020, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HAL_TIMESTAMP_READ		CTL_CODE(FILE_DEVICE_HAL, 4021, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HAL_VENDOR_ID_READ		CTL_CODE(FILE_DEVICE_HAL, 4022, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HAL_CUSTOMER_ID_READ		CTL_CODE(FILE_DEVICE_HAL, 4023, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HAL_BOARD_STATE_READ		CTL_CODE(FILE_DEVICE_HAL, 4024, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HAL_WATCHDOG_GET			CTL_CODE(FILE_DEVICE_HAL, 4025, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HAL_JTAG_ID_READ			CTL_CODE(FILE_DEVICE_HAL, 4026, METHOD_BUFFERED, FILE_ANY_ACCESS)


#endif		//__BSP_DRIVERS_H