;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this sample source code is subject to the terms of the Microsoft
; license agreement under which you licensed this sample source code. If
; you did not accept the terms of the license agreement, you are not
; authorized to use this sample source code. For the terms of the license,
; please see the license agreement between you and Microsoft or, if applicable,
; see the LICENSE.RTF on your install media or the root of your tools installation.
; THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
;
;------------------------------------------------------------------------------
;
;  File:  omap5912_config.inc
;
;  This file defines offset addresses for CONFIG registers. 
;
OMAP5912_CONFIG_FUNC_MUX_CTRL_0         EQU    0x00
OMAP5912_CONFIG_FUNC_MUX_CTRL_1         EQU    0x04
OMAP5912_CONFIG_FUNC_MUX_CTRL_2         EQU    0x08
OMAP5912_CONFIG_COMP_MODE_CTRL_0        EQU    0x0C
OMAP5912_CONFIG_FUNC_MUX_CTRL_3         EQU    0x10
OMAP5912_CONFIG_FUNC_MUX_CTRL_4         EQU    0x14
OMAP5912_CONFIG_FUNC_MUX_CTRL_5         EQU    0x18
OMAP5912_CONFIG_FUNC_MUX_CTRL_6         EQU    0x1C
OMAP5912_CONFIG_FUNC_MUX_CTRL_7         EQU    0x20
OMAP5912_CONFIG_FUNC_MUX_CTRL_8         EQU    0x24
OMAP5912_CONFIG_FUNC_MUX_CTRL_9         EQU    0x28
OMAP5912_CONFIG_FUNC_MUX_CTRL_A         EQU    0x2C
OMAP5912_CONFIG_FUNC_MUX_CTRL_B         EQU    0x30
OMAP5912_CONFIG_FUNC_MUX_CTRL_C         EQU    0x34
OMAP5912_CONFIG_FUNC_MUX_CTRL_D         EQU    0x38
OMAP5912_CONFIG_PULL_DWN_CTRL_0         EQU    0x40
OMAP5912_CONFIG_PULL_DWN_CTRL_1         EQU    0x44
OMAP5912_CONFIG_PULL_DWN_CTRL_2         EQU    0x48
OMAP5912_CONFIG_PULL_DWN_CTRL_3         EQU    0x4C
OMAP5912_CONFIG_GATE_INH_CTRL_0         EQU    0x50
OMAP5912_CONFIG_CONF_REV                EQU    0x58
OMAP5912_CONFIG_VOLTAGE_CTRL_0          EQU    0x60
OMAP5912_CONFIG_USB_TRANSCEIVER_CTRL    EQU    0x64
OMAP5912_CONFIG_LDO_PWRDN_CBTRK         EQU    0x68
OMAP5912_CONFIG_TEST_DBG_CTRL_0         EQU    0x70
OMAP5912_CONFIG_MOD_CONF_CTRL_0         EQU    0x80
OMAP5912_CONFIG_FUNC_MUX_CTRL_E         EQU    0x90
OMAP5912_CONFIG_FUNC_MUX_CTRL_F         EQU    0x94
OMAP5912_CONFIG_FUNC_MUX_CTRL_10        EQU    0x98
OMAP5912_CONFIG_FUNC_MUX_CTRL_11        EQU    0x9C
OMAP5912_CONFIG_FUNC_MUX_CTRL_12        EQU    0xA0
OMAP5912_CONFIG_PULL_DWN_CTRL_4         EQU    0xAC
OMAP5912_CONFIG_PU_PD_SEL_0             EQU    0xB4
OMAP5912_CONFIG_PU_PD_SEL_1             EQU    0xB8
OMAP5912_CONFIG_PU_PD_SEL_2             EQU    0xBC
OMAP5912_CONFIG_PU_PD_SEL_3             EQU    0xC0
OMAP5912_CONFIG_PU_PD_SEL_4             EQU    0xC4
OMAP5912_CONFIG_FUNC_MUX_DSP_DMA_A      EQU    0xD0
OMAP5912_CONFIG_FUNC_MUX_DSP_DMA_B      EQU    0xD4
OMAP5912_CONFIG_FUNC_MUX_DSP_DMA_C      EQU    0xD8
OMAP5912_CONFIG_FUNC_MUX_DSP_DMA_D      EQU    0xDC
OMAP5912_CONFIG_FUNC_MUX_ARM_DMA_A      EQU    0xEC
OMAP5912_CONFIG_FUNC_MUX_ARM_DMA_B      EQU    0xF0
OMAP5912_CONFIG_FUNC_MUX_ARM_DMA_C      EQU    0xF4
OMAP5912_CONFIG_FUNC_MUX_ARM_DMA_D      EQU    0xF8
OMAP5912_CONFIG_FUNC_MUX_ARM_DMA_E      EQU    0xFC
OMAP5912_CONFIG_FUNC_MUX_ARM_DMA_F      EQU    0x100
OMAP5912_CONFIG_FUNC_MUX_ARM_DMA_G      EQU    0x104
OMAP5912_CONFIG_MOD_CONF_CTRL_1         EQU    0x110
OMAP5912_CONFIG_SECCTRL                 EQU    0x120
OMAP5912_CONFIG_CONF_STATUS             EQU    0x130
OMAP5912_CONFIG_RESET_CONTROL           EQU    0x140
OMAP5912_CONFIG_CONF_5912_CTRL          EQU    0x150

;------------------------------------------------------------------------------

                                                END

