;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this sample source code is subject to the terms of the Microsoft
; license agreement under which you licensed this sample source code. If
; you did not accept the terms of the license agreement, you are not
; authorized to use this sample source code. For the terms of the license,
; please see the license agreement between you and Microsoft or, if applicable,
; see the LICENSE.RTF on your install media or the root of your tools installation.
; THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
;
;------------------------------------------------------------------------------
;
;  Header:  omap5912.inc
;
	INCLUDE omap5912_base_regs.inc
	INCLUDE omap5912_emif.inc
	INCLUDE omap5912_ocpi.inc
	INCLUDE omap5912_ulpd.inc
	INCLUDE omap5912_clkm.inc
	INCLUDE omap5912_config.inc
	INCLUDE omap5912_tipb.inc
	INCLUDE omap5912_gpio.inc
	INCLUDE omap5912_wdog.inc
	INCLUDE omap5912_dma.inc
	INCLUDE omap5912_otg.inc
	INCLUDE omap5912_19swatch.inc

	END
