;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this sample source code is subject to the terms of the Microsoft
; license agreement under which you licensed this sample source code. If
; you did not accept the terms of the license agreement, you are not
; authorized to use this sample source code. For the terms of the license,
; please see the license agreement between you and Microsoft or, if applicable,
; see the LICENSE.RTF on your install media or the root of your tools installation.
; THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
;
;------------------------------------------------------------------------------
;
;  File:  omap2420_otg.inc
;
;  This file defines offset addresses for OTG registers.
;
OMAP2420_OTG_REV_REGS_OA                EQU     0x0000
OMAP2420_OTG_SYSCON_1_REGS_OA           EQU     0x0004
OMAP2420_OTG_SYSCON_2_REGS_OA           EQU     0x0008
OMAP2420_OTG_CTRL_REGS_OA               EQU     0x000C
OMAP2420_OTG_IRQ_EN_REGS_OA             EQU     0x0010
OMAP2420_OTG_IRQ_SRC_REGS_OA            EQU     0x0014
OMAP2420_OTG_OUTCTRL_REGS_OA            EQU     0x0018
OMAP2420_OTG_TEST_REGS_OA               EQU     0x0020
OMAP2420_VC_REGS_OA                     EQU     0x04FC

;------------------------------------------------------------------------------

                                        END
