//------------------------------------------------------------------------------
//
//  Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
//  Use of this source code is subject to the terms of the Microsoft end-user
//  license agreement (EULA) under which you licensed this SOFTWARE PRODUCT.
//  If you did not accept the terms of the EULA, you are not authorized to use
//  this source code. For a copy of the EULA, please see the LICENSE.RTF on your
//  install media.
//
//------------------------------------------------------------------------------
//
//  Copyright (C) 2007-2008, Freescale Semiconductor, Inc. All Rights Reserved.
//  THIS SOURCE CODE, AND ITS USE AND DISTRIBUTION, IS SUBJECT TO THE TERMS
//  AND CONDITIONS OF THE APPLICABLE LICENSE AGREEMENT
//
//------------------------------------------------------------------------------
//
//  File:  mx51_to2_ddk.h
//
//  Contains MX51 TO2 definitions to assist with driver development.
//
//------------------------------------------------------------------------------
#ifndef __MX51_TO2_DDK_H
#define __MX51_TO2_DDK_H

#if __cplusplus
extern "C" {
#endif

//------------------------------------------------------------------------------
// Types
typedef CSP_IOMUX_TO2_REGS  CSP_IOMUX_REGS;
typedef PCSP_IOMUX_TO2_REGS PCSP_IOMUX_REGS;


//-----------------------------------------------------------------------------
//
//  Type: DDK_IOMUX_PIN
//
//  Specifies the functional pin name used to configure the IOMUX SW_MUX_CTL.
//
//-----------------------------------------------------------------------------
typedef enum {
    DDK_IOMUX_PIN_EIM_DA0                                       = (0),
    DDK_IOMUX_PIN_EIM_DA1                                       = (1),
    DDK_IOMUX_PIN_EIM_DA2                                       = (2),
    DDK_IOMUX_PIN_EIM_DA3                                       = (3),
    DDK_IOMUX_PIN_EIM_DA4                                       = (4),
    DDK_IOMUX_PIN_EIM_DA5                                       = (5),
    DDK_IOMUX_PIN_EIM_DA6                                       = (6),
    DDK_IOMUX_PIN_EIM_DA7                                       = (7),
    DDK_IOMUX_PIN_EIM_DA8                                       = (8),
    DDK_IOMUX_PIN_EIM_DA9                                       = (9),
    DDK_IOMUX_PIN_EIM_DA10                                      = (10),
    DDK_IOMUX_PIN_EIM_DA11                                      = (11),
    DDK_IOMUX_PIN_EIM_DA12                                      = (12),
    DDK_IOMUX_PIN_EIM_DA13                                      = (13),
    DDK_IOMUX_PIN_EIM_DA14                                      = (14),
    DDK_IOMUX_PIN_EIM_DA15                                      = (15),
    DDK_IOMUX_PIN_EIM_D16                                       = (16),
    DDK_IOMUX_PIN_EIM_D17                                       = (17),
    DDK_IOMUX_PIN_EIM_D18                                       = (18),
    DDK_IOMUX_PIN_EIM_D19                                       = (19),
    DDK_IOMUX_PIN_EIM_D20                                       = (20),
    DDK_IOMUX_PIN_EIM_D21                                       = (21),
    DDK_IOMUX_PIN_EIM_D22                                       = (22),
    DDK_IOMUX_PIN_EIM_D23                                       = (23),
    DDK_IOMUX_PIN_EIM_D24                                       = (24),
    DDK_IOMUX_PIN_EIM_D25                                       = (25),
    DDK_IOMUX_PIN_EIM_D26                                       = (26),
    DDK_IOMUX_PIN_EIM_D27                                       = (27),
    DDK_IOMUX_PIN_EIM_D28                                       = (28),
    DDK_IOMUX_PIN_EIM_D29                                       = (29),
    DDK_IOMUX_PIN_EIM_D30                                       = (30),
    DDK_IOMUX_PIN_EIM_D31                                       = (31),
    DDK_IOMUX_PIN_EIM_A16                                       = (32),
    DDK_IOMUX_PIN_EIM_A17                                       = (33),
    DDK_IOMUX_PIN_EIM_A18                                       = (34),
    DDK_IOMUX_PIN_EIM_A19                                       = (35),
    DDK_IOMUX_PIN_EIM_A20                                       = (36),
    DDK_IOMUX_PIN_EIM_A21                                       = (37),
    DDK_IOMUX_PIN_EIM_A22                                       = (38),
    DDK_IOMUX_PIN_EIM_A23                                       = (39),
    DDK_IOMUX_PIN_EIM_A24                                       = (40),
    DDK_IOMUX_PIN_EIM_A25                                       = (41),
    DDK_IOMUX_PIN_EIM_A26                                       = (42),
    DDK_IOMUX_PIN_EIM_A27                                       = (43),
    DDK_IOMUX_PIN_EIM_EB0                                       = (44),
    DDK_IOMUX_PIN_EIM_EB1                                       = (45),
    DDK_IOMUX_PIN_EIM_EB2                                       = (46),
    DDK_IOMUX_PIN_EIM_EB3                                       = (47),
    DDK_IOMUX_PIN_EIM_OE                                        = (48),
    DDK_IOMUX_PIN_EIM_CS0                                       = (49),
    DDK_IOMUX_PIN_EIM_CS1                                       = (50),
    DDK_IOMUX_PIN_EIM_CS2                                       = (51),
    DDK_IOMUX_PIN_EIM_CS3                                       = (52),
    DDK_IOMUX_PIN_EIM_CS4                                       = (53),
    DDK_IOMUX_PIN_EIM_CS5                                       = (54),
    DDK_IOMUX_PIN_EIM_DTACK                                     = (55),
    DDK_IOMUX_PIN_EIM_LBA                                       = (56),
    DDK_IOMUX_PIN_EIM_CRE                                       = (57),
    DDK_IOMUX_PIN_DRAM_CS1                                      = (58),
    DDK_IOMUX_PIN_NANDF_WE_B                                    = (59),
    DDK_IOMUX_PIN_NANDF_RE_B                                    = (60),
    DDK_IOMUX_PIN_NANDF_ALE                                     = (61),
    DDK_IOMUX_PIN_NANDF_CLE                                     = (62),
    DDK_IOMUX_PIN_NANDF_WP_B                                    = (63),
    DDK_IOMUX_PIN_NANDF_RB0                                     = (64),
    DDK_IOMUX_PIN_NANDF_RB1                                     = (65),
    DDK_IOMUX_PIN_NANDF_RB2                                     = (66),
    DDK_IOMUX_PIN_NANDF_RB3                                     = (67),
    DDK_IOMUX_PIN_GPIO_NAND                                     = (68),
    DDK_IOMUX_PIN_NANDF_CS0                                     = (69),
    DDK_IOMUX_PIN_NANDF_CS1                                     = (70),
    DDK_IOMUX_PIN_NANDF_CS2                                     = (71),
    DDK_IOMUX_PIN_NANDF_CS3                                     = (72),
    DDK_IOMUX_PIN_NANDF_CS4                                     = (73),
    DDK_IOMUX_PIN_NANDF_CS5                                     = (74),
    DDK_IOMUX_PIN_NANDF_CS6                                     = (75),
    DDK_IOMUX_PIN_NANDF_CS7                                     = (76),
    DDK_IOMUX_PIN_NANDF_RDY_INT                                 = (77),
    DDK_IOMUX_PIN_NANDF_D15                                     = (78),
    DDK_IOMUX_PIN_NANDF_D14                                     = (79),
    DDK_IOMUX_PIN_NANDF_D13                                     = (80),
    DDK_IOMUX_PIN_NANDF_D12                                     = (81),
    DDK_IOMUX_PIN_NANDF_D11                                     = (82),
    DDK_IOMUX_PIN_NANDF_D10                                     = (83),
    DDK_IOMUX_PIN_NANDF_D9                                      = (84),
    DDK_IOMUX_PIN_NANDF_D8                                      = (85),
    DDK_IOMUX_PIN_NANDF_D7                                      = (86),
    DDK_IOMUX_PIN_NANDF_D6                                      = (87),
    DDK_IOMUX_PIN_NANDF_D5                                      = (88),
    DDK_IOMUX_PIN_NANDF_D4                                      = (89),
    DDK_IOMUX_PIN_NANDF_D3                                      = (90),
    DDK_IOMUX_PIN_NANDF_D2                                      = (91),
    DDK_IOMUX_PIN_NANDF_D1                                      = (92),
    DDK_IOMUX_PIN_NANDF_D0                                      = (93),
    DDK_IOMUX_PIN_CSI1_D8                                       = (94),
    DDK_IOMUX_PIN_CSI1_D9                                       = (95),
    DDK_IOMUX_PIN_CSI1_D10                                      = (96),
    DDK_IOMUX_PIN_CSI1_D11                                      = (97),
    DDK_IOMUX_PIN_CSI1_D12                                      = (98),
    DDK_IOMUX_PIN_CSI1_D13                                      = (99),
    DDK_IOMUX_PIN_CSI1_D14                                      = (100),
    DDK_IOMUX_PIN_CSI1_D15                                      = (101),
    DDK_IOMUX_PIN_CSI1_D16                                      = (102),
    DDK_IOMUX_PIN_CSI1_D17                                      = (103),
    DDK_IOMUX_PIN_CSI1_D18                                      = (104),
    DDK_IOMUX_PIN_CSI1_D19                                      = (105),
    DDK_IOMUX_PIN_CSI1_VSYNC                                    = (106),
    DDK_IOMUX_PIN_CSI1_HSYNC                                    = (107),
    DDK_IOMUX_PIN_CSI2_D12                                      = (108),
    DDK_IOMUX_PIN_CSI2_D13                                      = (109),
    DDK_IOMUX_PIN_CSI2_D14                                      = (110),
    DDK_IOMUX_PIN_CSI2_D15                                      = (111),
    DDK_IOMUX_PIN_CSI2_D16                                      = (112),
    DDK_IOMUX_PIN_CSI2_D17                                      = (113),
    DDK_IOMUX_PIN_CSI2_D18                                      = (114),
    DDK_IOMUX_PIN_CSI2_D19                                      = (115),
    DDK_IOMUX_PIN_CSI2_VSYNC                                    = (116),
    DDK_IOMUX_PIN_CSI2_HSYNC                                    = (117),
    DDK_IOMUX_PIN_CSI2_PIXCLK                                   = (118),
    DDK_IOMUX_PIN_I2C1_CLK                                      = (119),
    DDK_IOMUX_PIN_I2C1_DAT                                      = (120),
    DDK_IOMUX_PIN_AUD3_BB_TXD                                   = (121),
    DDK_IOMUX_PIN_AUD3_BB_RXD                                   = (122),
    DDK_IOMUX_PIN_AUD3_BB_CK                                    = (123),
    DDK_IOMUX_PIN_AUD3_BB_FS                                    = (124),
    DDK_IOMUX_PIN_CSPI1_MOSI                                    = (125),
    DDK_IOMUX_PIN_CSPI1_MISO                                    = (126),
    DDK_IOMUX_PIN_CSPI1_SS0                                     = (127),
    DDK_IOMUX_PIN_CSPI1_SS1                                     = (128),
    DDK_IOMUX_PIN_CSPI1_RDY                                     = (129),
    DDK_IOMUX_PIN_CSPI1_SCLK                                    = (130),
    DDK_IOMUX_PIN_UART1_RXD                                     = (131),
    DDK_IOMUX_PIN_UART1_TXD                                     = (132),
    DDK_IOMUX_PIN_UART1_RTS                                     = (133),
    DDK_IOMUX_PIN_UART1_CTS                                     = (134),
    DDK_IOMUX_PIN_UART2_RXD                                     = (135),
    DDK_IOMUX_PIN_UART2_TXD                                     = (136),
    DDK_IOMUX_PIN_UART3_RXD                                     = (137),
    DDK_IOMUX_PIN_UART3_TXD                                     = (138),
    DDK_IOMUX_PIN_OWIRE_LINE                                    = (139),
    DDK_IOMUX_PIN_KEY_ROW0                                      = (140),
    DDK_IOMUX_PIN_KEY_ROW1                                      = (141),
    DDK_IOMUX_PIN_KEY_ROW2                                      = (142),
    DDK_IOMUX_PIN_KEY_ROW3                                      = (143),
    DDK_IOMUX_PIN_KEY_COL0                                      = (144),
    DDK_IOMUX_PIN_KEY_COL1                                      = (145),
    DDK_IOMUX_PIN_KEY_COL2                                      = (146),
    DDK_IOMUX_PIN_KEY_COL3                                      = (147),
    DDK_IOMUX_PIN_KEY_COL4                                      = (148),
    DDK_IOMUX_PIN_KEY_COL5                                      = (149),
    DDK_IOMUX_PIN_JTAG_DE_B                                     = (150),
    DDK_IOMUX_PIN_USBH1_CLK                                     = (151),
    DDK_IOMUX_PIN_USBH1_DIR                                     = (152),
    DDK_IOMUX_PIN_USBH1_STP                                     = (153),
    DDK_IOMUX_PIN_USBH1_NXT                                     = (154),
    DDK_IOMUX_PIN_USBH1_DATA0                                   = (155),
    DDK_IOMUX_PIN_USBH1_DATA1                                   = (156),
    DDK_IOMUX_PIN_USBH1_DATA2                                   = (157),
    DDK_IOMUX_PIN_USBH1_DATA3                                   = (158),
    DDK_IOMUX_PIN_USBH1_DATA4                                   = (159),
    DDK_IOMUX_PIN_USBH1_DATA5                                   = (160),
    DDK_IOMUX_PIN_USBH1_DATA6                                   = (161),
    DDK_IOMUX_PIN_USBH1_DATA7                                   = (162),
    DDK_IOMUX_PIN_DI1_PIN11                                     = (163),
    DDK_IOMUX_PIN_DI1_PIN12                                     = (164),
    DDK_IOMUX_PIN_DI1_PIN13                                     = (165),
    DDK_IOMUX_PIN_DI1_D0_CS                                     = (166),
    DDK_IOMUX_PIN_DI1_D1_CS                                     = (167),
    DDK_IOMUX_PIN_DISPB2_SER_DIN                                = (168),
    DDK_IOMUX_PIN_DISPB2_SER_DIO                                = (169),
    DDK_IOMUX_PIN_DISPB2_SER_CLK                                = (170),
    DDK_IOMUX_PIN_DISPB2_SER_RS                                 = (171),
    DDK_IOMUX_PIN_DISP1_DAT0                                    = (172),
    DDK_IOMUX_PIN_DISP1_DAT1                                    = (173),
    DDK_IOMUX_PIN_DISP1_DAT2                                    = (174),
    DDK_IOMUX_PIN_DISP1_DAT3                                    = (175),
    DDK_IOMUX_PIN_DISP1_DAT4                                    = (176),
    DDK_IOMUX_PIN_DISP1_DAT5                                    = (177),
    DDK_IOMUX_PIN_DISP1_DAT6                                    = (178),
    DDK_IOMUX_PIN_DISP1_DAT7                                    = (179),
    DDK_IOMUX_PIN_DISP1_DAT8                                    = (180),
    DDK_IOMUX_PIN_DISP1_DAT9                                    = (181),
    DDK_IOMUX_PIN_DISP1_DAT10                                   = (182),
    DDK_IOMUX_PIN_DISP1_DAT11                                   = (183),
    DDK_IOMUX_PIN_DISP1_DAT12                                   = (184),
    DDK_IOMUX_PIN_DISP1_DAT13                                   = (185),
    DDK_IOMUX_PIN_DISP1_DAT14                                   = (186),
    DDK_IOMUX_PIN_DISP1_DAT15                                   = (187),
    DDK_IOMUX_PIN_DISP1_DAT16                                   = (188),
    DDK_IOMUX_PIN_DISP1_DAT17                                   = (189),
    DDK_IOMUX_PIN_DISP1_DAT18                                   = (190),
    DDK_IOMUX_PIN_DISP1_DAT19                                   = (191),
    DDK_IOMUX_PIN_DISP1_DAT20                                   = (192),
    DDK_IOMUX_PIN_DISP1_DAT21                                   = (193),
    DDK_IOMUX_PIN_DISP1_DAT22                                   = (194),
    DDK_IOMUX_PIN_DISP1_DAT23                                   = (195),
    DDK_IOMUX_PIN_DI1_PIN3                                      = (196),
    DDK_IOMUX_PIN_DI1_PIN2                                      = (197),
    DDK_IOMUX_PIN_DI_GP1                                        = (198),
    DDK_IOMUX_PIN_DI_GP2                                        = (199),
    DDK_IOMUX_PIN_DI_GP3                                        = (200),
    DDK_IOMUX_PIN_DI2_PIN4                                      = (201),
    DDK_IOMUX_PIN_DI2_PIN2                                      = (202),
    DDK_IOMUX_PIN_DI2_PIN3                                      = (203),
    DDK_IOMUX_PIN_DI2_DISP_CLK                                  = (204),
    DDK_IOMUX_PIN_DI_GP4                                        = (205),
    DDK_IOMUX_PIN_DISP2_DAT0                                    = (206),
    DDK_IOMUX_PIN_DISP2_DAT1                                    = (207),
    DDK_IOMUX_PIN_DISP2_DAT2                                    = (208),
    DDK_IOMUX_PIN_DISP2_DAT3                                    = (209),
    DDK_IOMUX_PIN_DISP2_DAT4                                    = (210),
    DDK_IOMUX_PIN_DISP2_DAT5                                    = (211),
    DDK_IOMUX_PIN_DISP2_DAT6                                    = (212),
    DDK_IOMUX_PIN_DISP2_DAT7                                    = (213),
    DDK_IOMUX_PIN_DISP2_DAT8                                    = (214),
    DDK_IOMUX_PIN_DISP2_DAT9                                    = (215),
    DDK_IOMUX_PIN_DISP2_DAT10                                   = (216),
    DDK_IOMUX_PIN_DISP2_DAT11                                   = (217),
    DDK_IOMUX_PIN_DISP2_DAT12                                   = (218),
    DDK_IOMUX_PIN_DISP2_DAT13                                   = (219),
    DDK_IOMUX_PIN_DISP2_DAT14                                   = (220),
    DDK_IOMUX_PIN_DISP2_DAT15                                   = (221),
    DDK_IOMUX_PIN_SD1_CMD                                       = (222),
    DDK_IOMUX_PIN_SD1_CLK                                       = (223),
    DDK_IOMUX_PIN_SD1_DATA0                                     = (224),
    DDK_IOMUX_PIN_SD1_DATA1                                     = (225),
    DDK_IOMUX_PIN_SD1_DATA2                                     = (226),
    DDK_IOMUX_PIN_SD1_DATA3                                     = (227),
    DDK_IOMUX_PIN_GPIO1_0                                       = (228),
    DDK_IOMUX_PIN_GPIO1_1                                       = (229),
    DDK_IOMUX_PIN_SD2_CMD                                       = (230),
    DDK_IOMUX_PIN_SD2_CLK                                       = (231),
    DDK_IOMUX_PIN_SD2_DATA0                                     = (232),
    DDK_IOMUX_PIN_SD2_DATA1                                     = (233),
    DDK_IOMUX_PIN_SD2_DATA2                                     = (234),
    DDK_IOMUX_PIN_SD2_DATA3                                     = (235),
    DDK_IOMUX_PIN_GPIO1_2                                       = (236),
    DDK_IOMUX_PIN_GPIO1_3                                       = (237),
    DDK_IOMUX_PIN_PMIC_INT_REQ                                  = (238),
    DDK_IOMUX_PIN_GPIO1_4                                       = (239),
    DDK_IOMUX_PIN_GPIO1_5                                       = (240),
    DDK_IOMUX_PIN_GPIO1_6                                       = (241),
    DDK_IOMUX_PIN_GPIO1_7                                       = (242),
    DDK_IOMUX_PIN_GPIO1_8                                       = (243),
    DDK_IOMUX_PIN_GPIO1_9                                       = (244)
} DDK_IOMUX_PIN;


//-----------------------------------------------------------------------------
//
//  Type: DDK_IOMUX_SELECT_INPUT
//
//  Specifies the ports that have select input configuration.
//
//-----------------------------------------------------------------------------
typedef enum {
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P4_INPUT_DA_AMX               = (0),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P4_INPUT_DB_AMX               = (1),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P4_INPUT_TXCLK_AMX            = (2),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P4_INPUT_TXFS_AMX             = (3),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P5_INPUT_DA_AMX               = (4),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P5_INPUT_DB_AMX               = (5),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P5_INPUT_RXCLK_AMX            = (6),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P5_INPUT_RXFS_AMX             = (7),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P5_INPUT_TXCLK_AMX            = (8),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P5_INPUT_TXFS_AMX             = (9),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P6_INPUT_DA_AMX               = (10),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P6_INPUT_DB_AMX               = (11),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P6_INPUT_RXCLK_AMX            = (12),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P6_INPUT_RXFS_AMX             = (13),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P6_INPUT_TXCLK_AMX            = (14),
    DDK_IOMUX_SELECT_INPUT_AUDMUX_P6_INPUT_TXFS_AMX             = (15),
    DDK_IOMUX_SELECT_INPUT_CCM_IPP_DI0_CLK                      = (16),
    DDK_IOMUX_SELECT_INPUT_CCM_IPP_DI1_CLK                      = (17),
    DDK_IOMUX_SELECT_INPUT_CCM_PLL1_BYPASS_CLK                  = (18),
    DDK_IOMUX_SELECT_INPUT_CCM_PLL2_BYPASS_CLK                  = (19),
    DDK_IOMUX_SELECT_INPUT_CSPI_IPP_CSPI_CLK_IN                 = (20),
    DDK_IOMUX_SELECT_INPUT_CSPI_IPP_IND_MISO                    = (21),
    DDK_IOMUX_SELECT_INPUT_CSPI_IPP_IND_MOSI                    = (22),
    DDK_IOMUX_SELECT_INPUT_CSPI_IPP_IND_SS1_B                   = (23),
    DDK_IOMUX_SELECT_INPUT_CSPI_IPP_IND_SS2_B                   = (24),
    DDK_IOMUX_SELECT_INPUT_CSPI_IPP_IND_SS3_B                   = (25),
    DDK_IOMUX_SELECT_INPUT_DPLLIP1_L1T_TOG_EN                   = (26),
    DDK_IOMUX_SELECT_INPUT_ECSPI2_IPP_IND_SS_B_1                = (27),
    DDK_IOMUX_SELECT_INPUT_ECSPI2_IPP_IND_SS_B_3                = (28),
    DDK_IOMUX_SELECT_INPUT_EMI_IPP_IND_RDY_INT                  = (29),
    DDK_IOMUX_SELECT_INPUT_ESDHC3_IPP_DAT0_IN                   = (30),
    DDK_IOMUX_SELECT_INPUT_ESDHC3_IPP_DAT1_IN                   = (31),
    DDK_IOMUX_SELECT_INPUT_ESDHC3_IPP_DAT2_IN                   = (32),
    DDK_IOMUX_SELECT_INPUT_ESDHC3_IPP_DAT3_IN                   = (33),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_COL                          = (34),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_CRS                          = (35),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_MDI                          = (36),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_RDATA_0                      = (37),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_RDATA_1                      = (38),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_RDATA_2                      = (39),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_RDATA_3                      = (40),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_RX_CLK                       = (41),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_RX_DV                        = (42),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_RX_ER                        = (43),
    DDK_IOMUX_SELECT_INPUT_FEC_FEC_TX_CLK                       = (44),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_1                 = (45),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_2                 = (46),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_3                 = (47),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_4                 = (48),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_5                 = (49),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_6                 = (50),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_7                 = (51),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_8                 = (52),
    DDK_IOMUX_SELECT_INPUT_GPIO3_IPP_IND_G_IN_12                = (53),
    DDK_IOMUX_SELECT_INPUT_HSC_MIPI_MIX_IPP_IND_SENS1_DATA      = (54),
    DDK_IOMUX_SELECT_INPUT_HSC_MIPI_MIX_IPP_IND_SENS2_DATA      = (55),
    DDK_IOMUX_SELECT_INPUT_HSC_MIPI_MIX_PAR0_VSYNC              = (56),
    DDK_IOMUX_SELECT_INPUT_HSC_MIPI_MIX_PAR1_DI_WAIT            = (57),
    DDK_IOMUX_SELECT_INPUT_HSC_MIPI_MIX_PAR_SISG_TRIG           = (58),
    DDK_IOMUX_SELECT_INPUT_I2C1_IPP_SCL_IN                      = (59),
    DDK_IOMUX_SELECT_INPUT_I2C1_IPP_SDA_IN                      = (60),
    DDK_IOMUX_SELECT_INPUT_I2C2_IPP_SCL_IN                      = (61),
    DDK_IOMUX_SELECT_INPUT_I2C2_IPP_SDA_IN                      = (62),
    DDK_IOMUX_SELECT_INPUT_IPU_IPP_DI_0_IND_DISPB_SD_D          = (63),
    DDK_IOMUX_SELECT_INPUT_IPU_IPP_DI_1_IND_DISPB_SD_D          = (64),
    DDK_IOMUX_SELECT_INPUT_KPP_IPP_IND_COL_6                    = (65),
    DDK_IOMUX_SELECT_INPUT_KPP_IPP_IND_COL_7                    = (66),
    DDK_IOMUX_SELECT_INPUT_KPP_IPP_IND_ROW_4                    = (67),
    DDK_IOMUX_SELECT_INPUT_KPP_IPP_IND_ROW_5                    = (68),
    DDK_IOMUX_SELECT_INPUT_KPP_IPP_IND_ROW_6                    = (69),
    DDK_IOMUX_SELECT_INPUT_KPP_IPP_IND_ROW_7                    = (70),
    DDK_IOMUX_SELECT_INPUT_UART1_IPP_UART_RTS_B                 = (71),
    DDK_IOMUX_SELECT_INPUT_UART1_IPP_UART_RXD_MUX               = (72),
    DDK_IOMUX_SELECT_INPUT_UART2_IPP_UART_RTS_B                 = (73),
    DDK_IOMUX_SELECT_INPUT_UART2_IPP_UART_RXD_MUX               = (74),
    DDK_IOMUX_SELECT_INPUT_UART3_IPP_UART_RTS_B                 = (75),
    DDK_IOMUX_SELECT_INPUT_UART3_IPP_UART_RXD_MUX               = (76),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_CLK               = (77),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_0            = (78),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_1            = (79),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_2            = (80),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_3            = (81),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_4            = (82),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_5            = (83),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_6            = (84),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DATA_7            = (85),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_DIR               = (86),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_NXT               = (87),
    DDK_IOMUX_SELECT_INPUT_USBOH3_IPP_IND_UH3_STP               = (88)
} DDK_IOMUX_SELECT_INPUT;


//-----------------------------------------------------------------------------
//
//  Type: DDK_IOMUX_PAD
//
//  Specifies the functional pad name used to configure the IOMUX SW_PAD_CTL.
//
//-----------------------------------------------------------------------------
typedef enum {
    DDK_IOMUX_PAD_EIM_D16                                       = (0),
    DDK_IOMUX_PAD_EIM_D17                                       = (1),
    DDK_IOMUX_PAD_EIM_D18                                       = (2),
    DDK_IOMUX_PAD_EIM_D19                                       = (3),
    DDK_IOMUX_PAD_EIM_D20                                       = (4),
    DDK_IOMUX_PAD_EIM_D21                                       = (5),
    DDK_IOMUX_PAD_EIM_D22                                       = (6),
    DDK_IOMUX_PAD_EIM_D23                                       = (7),
    DDK_IOMUX_PAD_EIM_D24                                       = (8),
    DDK_IOMUX_PAD_EIM_D25                                       = (9),
    DDK_IOMUX_PAD_EIM_D26                                       = (10),
    DDK_IOMUX_PAD_EIM_D27                                       = (11),
    DDK_IOMUX_PAD_EIM_D28                                       = (12),
    DDK_IOMUX_PAD_EIM_D29                                       = (13),
    DDK_IOMUX_PAD_EIM_D30                                       = (14),
    DDK_IOMUX_PAD_EIM_D31                                       = (15),
    DDK_IOMUX_PAD_EIM_A16                                       = (16),
    DDK_IOMUX_PAD_EIM_A17                                       = (17),
    DDK_IOMUX_PAD_EIM_A18                                       = (18),
    DDK_IOMUX_PAD_EIM_A19                                       = (19),
    DDK_IOMUX_PAD_EIM_A20                                       = (20),
    DDK_IOMUX_PAD_EIM_A21                                       = (21),
    DDK_IOMUX_PAD_EIM_A22                                       = (22),
    DDK_IOMUX_PAD_EIM_A23                                       = (23),
    DDK_IOMUX_PAD_EIM_A24                                       = (24),
    DDK_IOMUX_PAD_EIM_A25                                       = (25),
    DDK_IOMUX_PAD_EIM_A26                                       = (26),
    DDK_IOMUX_PAD_EIM_A27                                       = (27),
    DDK_IOMUX_PAD_EIM_EB0                                       = (28),
    DDK_IOMUX_PAD_EIM_EB1                                       = (29),
    DDK_IOMUX_PAD_EIM_EB2                                       = (30),
    DDK_IOMUX_PAD_EIM_EB3                                       = (31),
    DDK_IOMUX_PAD_EIM_OE                                        = (32),
    DDK_IOMUX_PAD_EIM_CS0                                       = (33),
    DDK_IOMUX_PAD_EIM_CS1                                       = (34),
    DDK_IOMUX_PAD_EIM_CS2                                       = (35),
    DDK_IOMUX_PAD_EIM_CS3                                       = (36),
    DDK_IOMUX_PAD_EIM_CS4                                       = (37),
    DDK_IOMUX_PAD_EIM_CS5                                       = (38),
    DDK_IOMUX_PAD_EIM_DTACK                                     = (39),
    DDK_IOMUX_PAD_EIM_WAIT                                      = (40),
    DDK_IOMUX_PAD_EIM_LBA                                       = (41),
    DDK_IOMUX_PAD_EIM_BCLK                                      = (42),
    DDK_IOMUX_PAD_EIM_RW                                        = (43),
    DDK_IOMUX_PAD_EIM_CRE                                       = (44),
    DDK_IOMUX_PAD_DRAM_RAS                                      = (45),
    DDK_IOMUX_PAD_DRAM_CAS                                      = (46),
    DDK_IOMUX_PAD_DRAM_SDWE                                     = (47),
    DDK_IOMUX_PAD_DRAM_SDCKE0                                   = (48),
    DDK_IOMUX_PAD_DRAM_SDCKE1                                   = (49),
    DDK_IOMUX_PAD_DRAM_SDCLK                                    = (50),
    DDK_IOMUX_PAD_DRAM_SDQS0                                    = (51),
    DDK_IOMUX_PAD_DRAM_SDQS1                                    = (52),
    DDK_IOMUX_PAD_DRAM_SDQS2                                    = (53),
    DDK_IOMUX_PAD_DRAM_SDQS3                                    = (54),
    DDK_IOMUX_PAD_DRAM_CS0                                      = (55),
    DDK_IOMUX_PAD_DRAM_CS1                                      = (56),
    DDK_IOMUX_PAD_DRAM_DQM0                                     = (57),
    DDK_IOMUX_PAD_DRAM_DQM1                                     = (58),
    DDK_IOMUX_PAD_DRAM_DQM2                                     = (59),
    DDK_IOMUX_PAD_DRAM_DQM3                                     = (60),
    DDK_IOMUX_PAD_NANDF_WE_B                                    = (61),
    DDK_IOMUX_PAD_NANDF_RE_B                                    = (62),
    DDK_IOMUX_PAD_NANDF_ALE                                     = (63),
    DDK_IOMUX_PAD_NANDF_CLE                                     = (64),
    DDK_IOMUX_PAD_NANDF_WP_B                                    = (65),
    DDK_IOMUX_PAD_NANDF_RB0                                     = (66),
    DDK_IOMUX_PAD_NANDF_RB1                                     = (67),
    DDK_IOMUX_PAD_NANDF_RB2                                     = (68),
    DDK_IOMUX_PAD_NANDF_RB3                                     = (69),
    DDK_IOMUX_PAD_EIM_SDBA2                                     = (70),
    DDK_IOMUX_PAD_EIM_SDODT1                                    = (71),
    DDK_IOMUX_PAD_EIM_SDODT0                                    = (72),
    DDK_IOMUX_PAD_GPIO_NAND                                     = (73),
    DDK_IOMUX_PAD_NANDF_CS0                                     = (74),
    DDK_IOMUX_PAD_NANDF_CS1                                     = (75),
    DDK_IOMUX_PAD_NANDF_CS2                                     = (76),
    DDK_IOMUX_PAD_NANDF_CS3                                     = (77),
    DDK_IOMUX_PAD_NANDF_CS4                                     = (78),
    DDK_IOMUX_PAD_NANDF_CS5                                     = (79),
    DDK_IOMUX_PAD_NANDF_CS6                                     = (80),
    DDK_IOMUX_PAD_NANDF_CS7                                     = (81),
    DDK_IOMUX_PAD_NANDF_RDY_INT                                 = (82),
    DDK_IOMUX_PAD_NANDF_D15                                     = (83),
    DDK_IOMUX_PAD_NANDF_D14                                     = (84),
    DDK_IOMUX_PAD_NANDF_D13                                     = (85),
    DDK_IOMUX_PAD_NANDF_D12                                     = (86),
    DDK_IOMUX_PAD_NANDF_D11                                     = (87),
    DDK_IOMUX_PAD_NANDF_D10                                     = (88),
    DDK_IOMUX_PAD_NANDF_D9                                      = (89),
    DDK_IOMUX_PAD_NANDF_D8                                      = (90),
    DDK_IOMUX_PAD_NANDF_D7                                      = (91),
    DDK_IOMUX_PAD_NANDF_D6                                      = (92),
    DDK_IOMUX_PAD_NANDF_D5                                      = (93),
    DDK_IOMUX_PAD_NANDF_D4                                      = (94),
    DDK_IOMUX_PAD_NANDF_D3                                      = (95),
    DDK_IOMUX_PAD_NANDF_D2                                      = (96),
    DDK_IOMUX_PAD_NANDF_D1                                      = (97),
    DDK_IOMUX_PAD_NANDF_D0                                      = (98),
    DDK_IOMUX_PAD_CSI1_D8                                       = (99),
    DDK_IOMUX_PAD_CSI1_D9                                       = (100),
    DDK_IOMUX_PAD_CSI1_D10                                      = (101),
    DDK_IOMUX_PAD_CSI1_D11                                      = (102),
    DDK_IOMUX_PAD_CSI1_D12                                      = (103),
    DDK_IOMUX_PAD_CSI1_D13                                      = (104),
    DDK_IOMUX_PAD_CSI1_D14                                      = (105),
    DDK_IOMUX_PAD_CSI1_D15                                      = (106),
    DDK_IOMUX_PAD_CSI1_D16                                      = (107),
    DDK_IOMUX_PAD_CSI1_D17                                      = (108),
    DDK_IOMUX_PAD_CSI1_D18                                      = (109),
    DDK_IOMUX_PAD_CSI1_D19                                      = (110),
    DDK_IOMUX_PAD_CSI1_VSYNC                                    = (111),
    DDK_IOMUX_PAD_CSI1_HSYNC                                    = (112),
    DDK_IOMUX_PAD_CSI1_PIXCLK                                   = (113),
    DDK_IOMUX_PAD_CSI1_MCLK                                     = (114),
    DDK_IOMUX_PAD_CSI2_D12                                      = (115),
    DDK_IOMUX_PAD_CSI2_D13                                      = (116),
    DDK_IOMUX_PAD_CSI2_D14                                      = (117),
    DDK_IOMUX_PAD_CSI2_D15                                      = (118),
    DDK_IOMUX_PAD_CSI2_D16                                      = (119),
    DDK_IOMUX_PAD_CSI2_D17                                      = (120),
    DDK_IOMUX_PAD_CSI2_D18                                      = (121),
    DDK_IOMUX_PAD_CSI2_D19                                      = (122),
    DDK_IOMUX_PAD_CSI2_VSYNC                                    = (123),
    DDK_IOMUX_PAD_CSI2_HSYNC                                    = (124),
    DDK_IOMUX_PAD_CSI2_PIXCLK                                   = (125),
    DDK_IOMUX_PAD_I2C1_CLK                                      = (126),
    DDK_IOMUX_PAD_I2C1_DAT                                      = (127),
    DDK_IOMUX_PAD_AUD3_BB_TXD                                   = (128),
    DDK_IOMUX_PAD_AUD3_BB_RXD                                   = (129),
    DDK_IOMUX_PAD_AUD3_BB_CK                                    = (130),
    DDK_IOMUX_PAD_AUD3_BB_FS                                    = (131),
    DDK_IOMUX_PAD_CSPI1_MOSI                                    = (132),
    DDK_IOMUX_PAD_CSPI1_MISO                                    = (133),
    DDK_IOMUX_PAD_CSPI1_SS0                                     = (134),
    DDK_IOMUX_PAD_CSPI1_SS1                                     = (135),
    DDK_IOMUX_PAD_CSPI1_RDY                                     = (136),
    DDK_IOMUX_PAD_CSPI1_SCLK                                    = (137),
    DDK_IOMUX_PAD_UART1_RXD                                     = (138),
    DDK_IOMUX_PAD_UART1_TXD                                     = (139),
    DDK_IOMUX_PAD_UART1_RTS                                     = (140),
    DDK_IOMUX_PAD_UART1_CTS                                     = (141),
    DDK_IOMUX_PAD_UART2_RXD                                     = (142),
    DDK_IOMUX_PAD_UART2_TXD                                     = (143),
    DDK_IOMUX_PAD_UART3_RXD                                     = (144),
    DDK_IOMUX_PAD_UART3_TXD                                     = (145),
    DDK_IOMUX_PAD_OWIRE_LINE                                    = (146),
    DDK_IOMUX_PAD_KEY_ROW0                                      = (147),
    DDK_IOMUX_PAD_KEY_ROW1                                      = (148),
    DDK_IOMUX_PAD_KEY_ROW2                                      = (149),
    DDK_IOMUX_PAD_KEY_ROW3                                      = (150),
    DDK_IOMUX_PAD_KEY_COL0                                      = (151),
    DDK_IOMUX_PAD_KEY_COL1                                      = (152),
    DDK_IOMUX_PAD_KEY_COL2                                      = (153),
    DDK_IOMUX_PAD_KEY_COL3                                      = (154),
    DDK_IOMUX_PAD_KEY_COL4                                      = (155),
    DDK_IOMUX_PAD_KEY_COL5                                      = (156),
    DDK_IOMUX_PAD_JTAG_TCK                                      = (157),
    DDK_IOMUX_PAD_JTAG_TMS                                      = (158),
    DDK_IOMUX_PAD_JTAG_TDI                                      = (159),
    DDK_IOMUX_PAD_JTAG_TRSTB                                    = (160),
    DDK_IOMUX_PAD_JTAG_MOD                                      = (161),
    DDK_IOMUX_PAD_USBH1_CLK                                     = (162),
    DDK_IOMUX_PAD_USBH1_DIR                                     = (163),
    DDK_IOMUX_PAD_USBH1_STP                                     = (164),
    DDK_IOMUX_PAD_USBH1_NXT                                     = (165),
    DDK_IOMUX_PAD_USBH1_DATA0                                   = (166),
    DDK_IOMUX_PAD_USBH1_DATA1                                   = (167),
    DDK_IOMUX_PAD_USBH1_DATA2                                   = (168),
    DDK_IOMUX_PAD_USBH1_DATA3                                   = (169),
    DDK_IOMUX_PAD_USBH1_DATA4                                   = (170),
    DDK_IOMUX_PAD_USBH1_DATA5                                   = (171),
    DDK_IOMUX_PAD_USBH1_DATA6                                   = (172),
    DDK_IOMUX_PAD_USBH1_DATA7                                   = (173),
    DDK_IOMUX_PAD_DI1_PIN11                                     = (174),
    DDK_IOMUX_PAD_DI1_PIN12                                     = (175),
    DDK_IOMUX_PAD_DI1_PIN13                                     = (176),
    DDK_IOMUX_PAD_DI1_D0_CS                                     = (177),
    DDK_IOMUX_PAD_DI1_D1_CS                                     = (178),
    DDK_IOMUX_PAD_DISPB2_SER_DIN                                = (179),
    DDK_IOMUX_PAD_DISPB2_SER_DIO                                = (180),
    DDK_IOMUX_PAD_DISPB2_SER_CLK                                = (181),
    DDK_IOMUX_PAD_DISPB2_SER_RS                                 = (182),
    DDK_IOMUX_PAD_DISP1_DAT0                                    = (183),
    DDK_IOMUX_PAD_DISP1_DAT1                                    = (184),
    DDK_IOMUX_PAD_DISP1_DAT2                                    = (185),
    DDK_IOMUX_PAD_DISP1_DAT3                                    = (186),
    DDK_IOMUX_PAD_DISP1_DAT4                                    = (187),
    DDK_IOMUX_PAD_DISP1_DAT5                                    = (188),
    DDK_IOMUX_PAD_DISP1_DAT6                                    = (189),
    DDK_IOMUX_PAD_DISP1_DAT7                                    = (190),
    DDK_IOMUX_PAD_DISP1_DAT8                                    = (191),
    DDK_IOMUX_PAD_DISP1_DAT9                                    = (192),
    DDK_IOMUX_PAD_DISP1_DAT10                                   = (193),
    DDK_IOMUX_PAD_DISP1_DAT11                                   = (194),
    DDK_IOMUX_PAD_DISP1_DAT12                                   = (195),
    DDK_IOMUX_PAD_DISP1_DAT13                                   = (196),
    DDK_IOMUX_PAD_DISP1_DAT14                                   = (197),
    DDK_IOMUX_PAD_DISP1_DAT15                                   = (198),
    DDK_IOMUX_PAD_DISP1_DAT16                                   = (199),
    DDK_IOMUX_PAD_DISP1_DAT17                                   = (200),
    DDK_IOMUX_PAD_DISP1_DAT18                                   = (201),
    DDK_IOMUX_PAD_DISP1_DAT19                                   = (202),
    DDK_IOMUX_PAD_DISP1_DAT20                                   = (203),
    DDK_IOMUX_PAD_DISP1_DAT21                                   = (204),
    DDK_IOMUX_PAD_DISP1_DAT22                                   = (205),
    DDK_IOMUX_PAD_DISP1_DAT23                                   = (206),
    DDK_IOMUX_PAD_DI1_PIN3                                      = (207),
    DDK_IOMUX_PAD_DI1_DISP_CLK                                  = (208),
    DDK_IOMUX_PAD_DI1_PIN2                                      = (209),
    DDK_IOMUX_PAD_DI1_PIN15                                     = (210),
    DDK_IOMUX_PAD_DI_GP1                                        = (211),
    DDK_IOMUX_PAD_DI_GP2                                        = (212),
    DDK_IOMUX_PAD_DI_GP3                                        = (213),
    DDK_IOMUX_PAD_DI2_PIN4                                      = (214),
    DDK_IOMUX_PAD_DI2_PIN2                                      = (215),
    DDK_IOMUX_PAD_DI2_PIN3                                      = (216),
    DDK_IOMUX_PAD_DI2_DISP_CLK                                  = (217),
    DDK_IOMUX_PAD_DI_GP4                                        = (218),
    DDK_IOMUX_PAD_DISP2_DAT0                                    = (219),
    DDK_IOMUX_PAD_DISP2_DAT1                                    = (220),
    DDK_IOMUX_PAD_DISP2_DAT2                                    = (221),
    DDK_IOMUX_PAD_DISP2_DAT3                                    = (222),
    DDK_IOMUX_PAD_DISP2_DAT4                                    = (223),
    DDK_IOMUX_PAD_DISP2_DAT5                                    = (224),
    DDK_IOMUX_PAD_DISP2_DAT6                                    = (225),
    DDK_IOMUX_PAD_DISP2_DAT7                                    = (226),
    DDK_IOMUX_PAD_DISP2_DAT8                                    = (227),
    DDK_IOMUX_PAD_DISP2_DAT9                                    = (228),
    DDK_IOMUX_PAD_DISP2_DAT10                                   = (229),
    DDK_IOMUX_PAD_DISP2_DAT11                                   = (230),
    DDK_IOMUX_PAD_DISP2_DAT12                                   = (231),
    DDK_IOMUX_PAD_DISP2_DAT13                                   = (232),
    DDK_IOMUX_PAD_DISP2_DAT14                                   = (233),
    DDK_IOMUX_PAD_DISP2_DAT15                                   = (234),
    DDK_IOMUX_PAD_SD1_CMD                                       = (235),
    DDK_IOMUX_PAD_SD1_CLK                                       = (236),
    DDK_IOMUX_PAD_SD1_DATA0                                     = (237),
    DDK_IOMUX_PAD_SD1_DATA1                                     = (238),
    DDK_IOMUX_PAD_SD1_DATA2                                     = (239),
    DDK_IOMUX_PAD_SD1_DATA3                                     = (240),
    DDK_IOMUX_PAD_GPIO1_0                                       = (241),
    DDK_IOMUX_PAD_GPIO1_1                                       = (242),
    DDK_IOMUX_PAD_SD2_CMD                                       = (243),
    DDK_IOMUX_PAD_SD2_CLK                                       = (244),
    DDK_IOMUX_PAD_SD2_DATA0                                     = (245),
    DDK_IOMUX_PAD_SD2_DATA1                                     = (246),
    DDK_IOMUX_PAD_SD2_DATA2                                     = (247),
    DDK_IOMUX_PAD_SD2_DATA3                                     = (248),
    DDK_IOMUX_PAD_GPIO1_2                                       = (249),
    DDK_IOMUX_PAD_GPIO1_3                                       = (250),
    DDK_IOMUX_PAD_RESET_IN_B                                    = (251),
    DDK_IOMUX_PAD_POR_B                                         = (252),
    DDK_IOMUX_PAD_BOOT_MODE1                                    = (253),
    DDK_IOMUX_PAD_BOOT_MODE0                                    = (254),
    DDK_IOMUX_PAD_PMIC_RDY                                      = (255),
    DDK_IOMUX_PAD_CKIL                                          = (256),
    DDK_IOMUX_PAD_PMIC_STBY_REQ                                 = (257),
    DDK_IOMUX_PAD_PMIC_ON_REQ                                   = (258),
    DDK_IOMUX_PAD_PMIC_INT_REQ                                  = (259),
    DDK_IOMUX_PAD_CLK_SS                                        = (260),
    DDK_IOMUX_PAD_GPIO1_4                                       = (261),
    DDK_IOMUX_PAD_GPIO1_5                                       = (262),
    DDK_IOMUX_PAD_GPIO1_6                                       = (263),
    DDK_IOMUX_PAD_GPIO1_7                                       = (264),
    DDK_IOMUX_PAD_GPIO1_8                                       = (265),
    DDK_IOMUX_PAD_GPIO1_9                                       = (266),
    DDK_IOMUX_PAD_GRP_CSI2_PKE0                                 = (267),
    DDK_IOMUX_PAD_GRP_DDRPKS                                    = (268),
    DDK_IOMUX_PAD_GRP_EIM_SR1                                   = (269),
    DDK_IOMUX_PAD_GRP_DISP2_PKE0                                = (270),
    DDK_IOMUX_PAD_GRP_DRAM_B4                                   = (271),
    DDK_IOMUX_PAD_GRP_INDDR                                     = (272),
    DDK_IOMUX_PAD_GRP_EIM_SR2                                   = (273),
    DDK_IOMUX_PAD_GRP_PKEDDR                                    = (274),
    DDK_IOMUX_PAD_GRP_DDR_A0                                    = (275),
    DDK_IOMUX_PAD_GRP_EMI_PKE0                                  = (276),
    DDK_IOMUX_PAD_GRP_EIM_SR3                                   = (277),
    DDK_IOMUX_PAD_GRP_DDR_A1                                    = (278),
    DDK_IOMUX_PAD_GRP_DDRAPUS                                   = (279),
    DDK_IOMUX_PAD_GRP_EIM_SR4                                   = (280),
    DDK_IOMUX_PAD_GRP_EMI_SR5                                   = (281),
    DDK_IOMUX_PAD_GRP_EMI_SR6                                   = (282),
    DDK_IOMUX_PAD_GRP_HYSDDR0                                   = (283),
    DDK_IOMUX_PAD_GRP_CSI1_PKE0                                 = (284),
    DDK_IOMUX_PAD_GRP_HYSDDR1                                   = (285),
    DDK_IOMUX_PAD_GRP_DISP1_PKE0                                = (286),
    DDK_IOMUX_PAD_GRP_HYSDDR2                                   = (287),
    DDK_IOMUX_PAD_GRP_HVDDR                                     = (288),
    DDK_IOMUX_PAD_GRP_HYSDDR3                                   = (289),
    DDK_IOMUX_PAD_GRP_DRAM_SR_B0                                = (290),
    DDK_IOMUX_PAD_GRP_DDRAPKS                                   = (291),
    DDK_IOMUX_PAD_GRP_DRAM_SR_B1                                = (292),
    DDK_IOMUX_PAD_GRP_DDRPUS                                    = (293),
    DDK_IOMUX_PAD_GRP_EIM_DS1                                   = (294),
    DDK_IOMUX_PAD_GRP_DRAM_SR_B2                                = (295),
    DDK_IOMUX_PAD_GRP_PKEADDR                                   = (296),
    DDK_IOMUX_PAD_GRP_EIM_DS2                                   = (297),
    DDK_IOMUX_PAD_GRP_EIM_DS3                                   = (298),
    DDK_IOMUX_PAD_GRP_DRAM_SR_B4                                = (299),
    DDK_IOMUX_PAD_GRP_INMODE1                                   = (300),
    DDK_IOMUX_PAD_GRP_DRAM_B0                                   = (301),
    DDK_IOMUX_PAD_GRP_EIM_DS4                                   = (302),
    DDK_IOMUX_PAD_GRP_DRAM_B1                                   = (303),
    DDK_IOMUX_PAD_GRP_DDR_SR_A0                                 = (304),
    DDK_IOMUX_PAD_GRP_EMI_DS5                                   = (305),
    DDK_IOMUX_PAD_GRP_DRAM_B2                                   = (306),
    DDK_IOMUX_PAD_GRP_DDR_SR_A1                                 = (307),
    DDK_IOMUX_PAD_GRP_EMI_DS6                                   = (308)
} DDK_IOMUX_PAD;
          
          
//------------------------------------------------------------------------------
// Functions

BOOL DDKIomuxSetPinMux(DDK_IOMUX_PIN pin, DDK_IOMUX_PIN_MUXMODE muxmode, 
    DDK_IOMUX_PIN_SION sion);
BOOL DDKIomuxGetPinMux(DDK_IOMUX_PIN pin, DDK_IOMUX_PIN_MUXMODE *pMuxmode, 
    DDK_IOMUX_PIN_SION *pSion);
BOOL DDKIomuxSetPadConfig(DDK_IOMUX_PAD pad, DDK_IOMUX_PAD_SLEW slew, 
    DDK_IOMUX_PAD_DRIVE drive, DDK_IOMUX_PAD_OPENDRAIN openDrain, 
    DDK_IOMUX_PAD_PULL pull, DDK_IOMUX_PAD_HYSTERESIS hysteresis, 
    DDK_IOMUX_PAD_INMODE inputMode, DDK_IOMUX_PAD_OUTVOLT outputVolt);
BOOL DDKIomuxGetPadConfig(DDK_IOMUX_PAD pad, DDK_IOMUX_PAD_SLEW *pSlew, 
    DDK_IOMUX_PAD_DRIVE *pDrive, DDK_IOMUX_PAD_OPENDRAIN *pOpenDrain, 
    DDK_IOMUX_PAD_PULL *pPull, DDK_IOMUX_PAD_HYSTERESIS *pHysteresis, 
    DDK_IOMUX_PAD_INMODE *pInputMode, DDK_IOMUX_PAD_OUTVOLT *pOutputVolt);
BOOL DDKIomuxSetGpr0(UINT32 data);
BOOL DDKIomuxSetGpr1(UINT32 data);
UINT32 DDKIomuxGetGpr0(VOID);
UINT32 DDKIomuxGetGpr1(VOID);
BOOL DDKIomuxSelectInput(DDK_IOMUX_SELECT_INPUT port, UINT32 daisy);


#if __cplusplus
}
#endif

#endif // __MX51_TO2_DDK_H
