;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this sample source code is subject to the terms of the Microsoft
; license agreement under which you licensed this sample source code. If
; you did not accept the terms of the license agreement, you are not
; authorized to use this sample source code. For the terms of the license,
; please see the license agreement between you and Microsoft or, if applicable,
; see the LICENSE.RTF on your install media or the root of your tools installation.
; THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
;
;;------------------------------------------------------------------------------
;;
;;  Copyright(c) 1998,1999 Renesas Technology Corp.
;;
;;------------------------------------------------------------------------------
;;
;;	File:   sh4.inc
;;
;;------------------------------------------------------------------------------

    .include    "sh4_bsc.inc"
    .include    "sh4_ccn.inc"
    .include    "sh4_cpg.inc"
    .include    "sh4_dmac.inc"
    .include    "sh4_intc.inc"
    .include    "sh4_rtc.inc"
    .include    "sh4_sci.inc"
    .include    "sh4_scif.inc"
    .include    "sh4_tmu.inc"
    .include    "sh4_def.inc"

