// All rights reserved ADENEO EMBEDDED 2010
/*
===============================================================================
*             Texas Instruments OMAP(TM) Platform Software
* (c) Copyright Texas Instruments, Incorporated. All Rights Reserved.
*
* Use of this software is controlled by the terms and conditions found
* in the license agreement under which this software has been supplied.
*
===============================================================================
*/
//  File: prcm_device.h

#include "prcm_priv.h"

DeviceLookupEntry s_rgDeviceLookupTable[] =
{
//{PWR_ALWAYSON,  CLKDMN_ALWON_L3_SLOW,  CLKDMN_SYSCLK6, 0,  PRCM_OFS(CM_ALWON_GPIO_0_CLKCTRL)  }, // AM_DEVICE_GPIO0,
//	{POWERDOMAIN           FCLK             ICLK        RefCnt   CLKCTRL 
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_MCASP0_CLKCTRL) },// AM_DEVICE_MCASP0,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_MCASP1_CLKCTRL) },// AM_DEVICE_MCASP1,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_MCASP2_CLKCTRL) },// AM_DEVICE_MCASP2,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK4, 0, 0                                 },// AM_DEVICE_MCASP3,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK4, 0, 0                                 },// AM_DEVICE_MCASP4,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK4, 0, 0                                 },// AM_DEVICE_MCASP5,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_MCBSP,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_I2C_02_CLKCTRL) },// AM_DEVICE_I2C0,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_I2C_13_CLKCTRL) },// AM_DEVICE_I2C1,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_I2C_02_CLKCTRL) },// AM_DEVICE_I2C2,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_I2C_13_CLKCTRL) },// AM_DEVICE_I2C3,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_SPI_CLKCTRL)	   },// AM_DEVICE_MCSPI0,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_SPI_CLKCTRL)    },// AM_DEVICE_MCSPI1,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_SPI_CLKCTRL)    },// AM_DEVICE_MCSPI2,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_SPI_CLKCTRL)    },// AM_DEVICE_MCSPI3,
    { PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_UART0,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_UART1,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_UART2,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_UART3,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_UART4,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_UART5,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_GPIO_0_CLKCTRL) },// AM_DEVICE_GPIO0,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_GPIO_1_CLKCTRL) },// AM_DEVICE_GPIO1,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_GPIO_1_CLKCTRL) },// AM_DEVICE_GPIO2,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW, CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_GPIO_1_CLKCTRL) },// AM_DEVICE_GPIO3,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER1,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER2,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER3,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER4,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER5,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER6,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER7,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN, CLKDMN_SYSCLK6, 0, 0                                 },// AM_DEVICE_TIMER8,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_SYNCTIMER32K,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW,  CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_SDIO_CLKCTRL)   },// AM_DEVICE_SDIO0,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW,  CLKDMN_SYSCLK6, 0, PRCM_OFS(CM_ALWON_SDIO_CLKCTRL)   },// AM_DEVICE_SDIO1,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_MMCHS0,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_MMCHS1,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_MMCHS2,
					
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_RTC,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_ELM,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_MAILBOX,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_SMARTREFLEX0,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_SMARTREFLEX1,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_SMARTREFLEX2,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_SMARTREFLEX3,
	{ PWR_ALWAYSON, CLKDMN_ALWON_ETHERNET, CLKDMN_NULL, PRCM_OFS(CM_ETHERNET_CLKSTCTRL) },// AM_DEVICE_EMACSW,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_SATA,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_DCAN0,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_DCAN1,
	{ PWR_ALWAYSON, CLKDMN_ALWON2_L3_SLOW,  CLKDMN_ALWON2_USB, 0, 0    },// AM_DEVICE_USB0,
	{ PWR_ALWAYSON, CLKDMN_ALWON2_L3_SLOW,  CLKDMN_ALWON2_USB, 0, 0    },// AM_DEVICE_USB1,
	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_ALT,

	{ PWR_HVAHD,	CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_HDVPSS,
	{ PWR_DSS,		CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_HDMI,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_WDT0,

	{ PWR_ALWAYSON, CLKDMN_ALWON_L3_SLOW,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_PATA,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_MMU,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_MMUCFG,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_OCMC_0,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_VCP,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_MPU,

	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_GPMC,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_TPCC,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_TPTC0,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_TPTC1,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_TPTC2,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_TPTC3,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_L4_HS,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_L4_LS

	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_DDR_PHYL0,
	{ PWR_ALWAYSON, CLKDMN_UNKNOWN,  CLKDMN_UNKNOWN, 0, 0    },// AM_DEVICE_DDR_PHYL1

};

//-----------------------------------------------------------------------------
static UINT s_rgActiveDomainDeviceCount[PWR_COUNT] = 
{
	0,	// PWR_ALWAYSON
	0,	// PWR_ISP
	0,	// PWR_GFX
	0,	// PWR_DSS       
	0,	// PWR_ACTIVE   
	0,	// PWR_HVAHD
};

