;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this source code is subject to the terms of the Microsoft end-user
; license agreement (EULA) under which you licensed this SOFTWARE PRODUCT.
; If you did not accept the terms of the EULA, you are not authorized to use
; this source code. For a copy of the EULA, please see the LICENSE.RTF on your
; install media.
;
;++
;
; Module Name:
;
;    bulverde.inc
;
; Abstract:
;
;  This header file defines only those registers required by the startup
;  code. All addresses are based off the physical addresses (PA) defined
;  in bulverde_base_reg.h (bulverde_base_reg.inc).
;
; Environment:
;
; Revision History:
;
;--
;
; Copyright © 2002-2003 Intel Corp.
;
;-------------------------------------------------------------------------------
;

; Include the base register definitions
;
	INCLUDE bulverde_base_regs.inc

    END
