;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this sample source code is subject to the terms of the Microsoft
; license agreement under which you licensed this sample source code. If
; you did not accept the terms of the license agreement, you are not
; authorized to use this sample source code. For the terms of the license,
; please see the license agreement between you and Microsoft or, if applicable,
; see the LICENSE.RTF on your install media or the root of your tools installation.
; THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
;
;------------------------------------------------------------------------------
;
;  Header:  omap2420.inc
;
	INCLUDE omap2420_base_regs.inc
	INCLUDE omap2420_ctrlpadconf.inc
	INCLUDE omap2420_gpio.inc
	INCLUDE omap2420_gpmc.inc
	INCLUDE omap2420_prcm.inc
	INCLUDE omap2420_sdram.inc
	INCLUDE omap2420_timer.inc
	INCLUDE omap2420_dma.inc
	INCLUDE omap2420_otg.inc
	INCLUDE omap2420_intc.inc

	END
