;
; Copyright (c) Microsoft Corporation.  All rights reserved.
;
;
; Use of this source code is subject to the terms of the Microsoft end-user
; license agreement (EULA) under which you licensed this SOFTWARE PRODUCT.
; If you did not accept the terms of the EULA, you are not authorized to use
; this source code. For a copy of the EULA, please see the LICENSE.RTF on your
; install media.
;
;-------------------------------------------------------------------------------
;
; Copyright (C) 2007-2008, Freescale Semiconductor, Inc. All Rights Reserved.
; THIS SOURCE CODE, AND ITS USE AND DISTRIBUTION, IS SUBJECT TO THE TERMS
; AND CONDITIONS OF THE APPLICABLE LICENSE AGREEMENT
;
;-------------------------------------------------------------------------------
;
;  File:  cleandclines.s
;
;
    INCLUDE kxarm.h
    INCLUDE armmacros.s
    INCLUDE oal_cache.inc

    IMPORT g_oalCacheInfo

    TEXTAREA

;-------------------------------------------------------------------------------
;
;  Function:  OALClearDCacheLines
;
    LEAF_ENTRY OALCleanDCacheLines

    ldr     r2, =g_oalCacheInfo
    ldr     r3, [r2, #L1DLineSize]

    ; ----- ARM errata #586323 -----
    ; Description:  Cache clean memory ops generated by either the Preload 
    ;   Engine or Clean by MVA to PoC instructions may corrupt memory.
    ;
    ; Workaround:  Convert all "Clean by MVA to Point of Coherency" operations to 
    ;   be instead "Clean and Invalidate by MVA to Point of Coherency".
    ;
; 10  mcr     p15, 0, r0, c7, c10, 1          ; clean entry
10  mcr     p15, 0, r0, c7, c14, 1          ; clean and invalidate entry
    add     r0, r0, r3                      ; move to next entry
    subs    r1, r1, r3
    bgt     %b10                            ; loop while > 0 bytes left

    mov     r2, #0
    DCD     0xF57FF04F                      ; DSB
    mcr     p15, 0, r2, c7, c5, 6           ; flush the BTAC

    RETURN

    END
