// All rights reserved ADENEO EMBEDDED 2010
/*
===============================================================================
*             Texas Instruments OMAP(TM) Platform Software
* (c) Copyright Texas Instruments, Incorporated. All Rights Reserved.
*
* Use of this software is controlled by the terms and conditions found
* in the license agreement under which this software has been supplied.
*
===============================================================================
*/
//
//  File:  am387x_clocks.h
//
//  This header defines all relevant clocks and power domains for am389x.
//
#ifndef __AM387X_CLOCKS_H
#define __AM387X_CLOCKS_H

#ifdef __cplusplus
extern "C" {
#endif

//------------------------------------------------------------------------------

/*
 * In AM387x the 20MHz crystal generates various root clks (main pll, audio pll, video pll and ddr pll)
 * From these root clks the SYSCLKs are generated by making use of dividers
 */


#define AM387X_GENERIC        0xFFFFFFFF

typedef enum {
	AM_DEVICE_MCASP0  = 0,
	AM_DEVICE_MCASP1,
	AM_DEVICE_MCASP2,
	AM_DEVICE_MCASP3,
	AM_DEVICE_MCASP4,
	AM_DEVICE_MCASP5,
	AM_DEVICE_MCBSP,
	AM_DEVICE_I2C0,
	AM_DEVICE_I2C1,
	AM_DEVICE_I2C2,
	AM_DEVICE_I2C3,
	AM_DEVICE_MCSPI0,
	AM_DEVICE_MCSPI1,
	AM_DEVICE_MCSPI2,
	AM_DEVICE_MCSPI3,
    AM_DEVICE_UART0,
    AM_DEVICE_UART1,
    AM_DEVICE_UART2,
    AM_DEVICE_UART3,
    AM_DEVICE_UART4,
    AM_DEVICE_UART5,
	AM_DEVICE_GPIO0,
	AM_DEVICE_GPIO1,
	AM_DEVICE_GPIO2,
	AM_DEVICE_GPIO3,
	AM_DEVICE_TIMER1,
	AM_DEVICE_TIMER2,
	AM_DEVICE_TIMER3,
	AM_DEVICE_TIMER4,
	AM_DEVICE_TIMER5,
	AM_DEVICE_TIMER6,
	AM_DEVICE_TIMER7,
	AM_DEVICE_TIMER8,
	AM_DEVICE_SYNCTIMER32K,
	AM_DEVICE_SDIO0,
	AM_DEVICE_SDIO1,
	AM_DEVICE_MMCHS0,
	AM_DEVICE_MMCHS1,
	AM_DEVICE_MMCHS2,
	AM_DEVICE_RTC,
	AM_DEVICE_ELM,
	AM_DEVICE_MAILBOX,
	AM_DEVICE_SMARTREFLEX0,
	AM_DEVICE_SMARTREFLEX1,
	AM_DEVICE_SMARTREFLEX2,
	AM_DEVICE_SMARTREFLEX3,
	AM_DEVICE_EMACSW,
	AM_DEVICE_SATA,
	AM_DEVICE_DCAN0,
	AM_DEVICE_DCAN1,
	AM_DEVICE_USB0,
	AM_DEVICE_USB1,
	AM_DEVICE_ALT,

	AM_DEVICE_HDVPSS,
	AM_DEVICE_HDMI,
	AM_DEVICE_WDT0,

	AM_DEVICE_PATA,
	AM_DEVICE_MMU,			// MMU domain
	AM_DEVICE_MMUCFG,		// MMUCFG domain
	AM_DEVICE_OCMC_0,
	AM_DEVICE_VCP,
	AM_DEVICE_MPU,

	AM_DEVICE_GPMC,
	AM_DEVICE_TPCC,
	AM_DEVICE_TPTC0,
	AM_DEVICE_TPTC1,
	AM_DEVICE_TPTC2,
	AM_DEVICE_TPTC3,
	AM_DEVICE_L4_HS,
	AM_DEVICE_L4_LS,

	AM_DEVICE_DDR_PHYL0,
	AM_DEVICE_DDR_PHYL1,

	AM_DEVICE_COUNT,
} AM387X_DEVICE_ID;

// For convenience
#define AM_DEVICE_MMC AM_DEVICE_SDIO

//-----------------------------------------------------------------------------

typedef enum {
    PWR_ALWAYSON = 0,
    PWR_ALWAYSON2,
    PWR_ISP,
    PWR_GFX,
    PWR_DSS,        
    PWR_ACTIVE,
    PWR_HVAHD,    
	PWR_COUNT
} PowerDomain_e;

typedef enum {
	CLKDMN_ALWON2_L3_MED,
	CLKDMN_ALWON2_PCIE,
	CLKDMN_ALWON2_TPPSS,
	CLKDMN_ALWON2_USB,
	CLKDMN_ALWON2_L3_SLOW,
	CLKDMN_ALWON2_L3_FAST,
	CLKDMN_ALWON2_MC,
	CLKDMN_SYSCLK6,
	CLKDMN_SYSCLK4,
	CLKDMN_ALWON_L3_SLOW,
	CLKDMN_ALWON_ETHERNET,
	CLKDMN_ALWON_L3_MED,
	CLKDMN_MMU,
	CLKDMN_MMU_CFG,
	CLKDMN_ALWON_OCMC_0,
	CLKDMN_ALWON_VCP,
	CLKDMN_ALWON_MPU,
	CLKDMN_ALWON_RTC,
	CLKDMN_ALWON_L3_FAST,
	CLKDMN_GEM,
	CLKDMN_HDVICP,
	CLKDMN_ISP,
	CLKDMN_HDVPSS,
	CLKDMN_GFX,
    CLKDMN_COUNT,
    CLKDMN_NULL = 0xfff,
    CLKDMN_UNKNOWN = 0xffff
} ClockDomain_e;



//-----------------------------------------------------------------------------

typedef enum {    
    kARM_L,
	kARM_M,
	kCORE_L,
	kCORE_M,
	kACTIVE_L,
	kACTIVE_M,
	kIVAHD_L,
	kIVAHD_M,
	kVDD_EXT,		//TODO: that is a temp definition.
					//      FIX the s_DpllTable table to set the correct VDD domains
    kVDD_COUNT,
} Vdd_e;

//------------------------------------------------------------------------------

typedef enum {    
	kAD_PLL,
	kDSP_PLL,
	kDSS_PLL,
	kISS_PLL,
	kIVA_PLL,
	kL3_PLL,
	kSGX_PLL,
	kUSB_PLL,
	kDDR_PLL,
	kVIDEO0_PLL,
	kHDMI_PLL,
	kVIDEO1_PLL,
	kAUDIO_PLL,
	kUNKNOWN_PLL,
    kDPLL_COUNT,
} Dpll_e;

//------------------------------------------------------------------------------
/* External clock sources to PRCM */
typedef enum {
	kRCOSC_32K_CK,			// [    32768]	
	kSYS_32K_CLKIN_CK,		// [    32768]
	kTCLKIN_CK,				// [    32768]
	kOSC0_CLKIN_CK,			// [ 20000000]
	kOSC1_CLKIN_CK,			// [ 22579000]
	kRTC_DIVIDER_CK,		// [    32768]
	kOSC1_X1_CK,			// [ 20000000]
	kXREF0_CK,				// [ 27000000]
	kXREF1_CK,				// [ 27000000]
	kXREF2_CK,				// [ 27000000]
	kTSI0_DCK_CK,			// [ 82000000]
	kTSI1_DCK_CK,			// [ 82000000]
	kEXTERNAL_CK,			// [ 50000000]
	kATL0_CLK_CK,			// [ 22579000]
	kATL1_CLK_CK,			// [ 22579000]
	kATL2_CLK_CK,			// [ 22579000]
	kATL3_CLK_CK,			// [ 22579000]
	kARM_DPLL_CK,			// [600000000]
	kDSP_DPLL_CK,			// [500000000]
	kSGX_DPLL_CK,			// [200000000]
	kHDVICP_DPLL_CK,		// [425000000] 
	kL3_DPLL_CK,			// [220000000]
	kISS_DPLL_CK,			// [400000000]
	kHDVPSS_DPLL_CK,		// [200000000]
	kDVI_CH1_CK,			// [166000000]
	kDVI_CH2_CK,			// [166000000]
	kDVI_CH3_CK,			// [166000000]
	kDVI_CH4_CK,			// [166000000]
	kDVOI1_CK,				// [162000000]
	kDVOI2_CK,				// [162000000]
	kUSB_DPLL_CK,			// [960000000]
	kDDR_DPLL_CK,			// [333000000]
	kVIDEO0_DPLL_CK,		// [ 54000000]
	kVIDEO1_DPLL_CK,		// [148500000]
	kHDMI_DPLL_CK,          // [186000000]
	kVIDEO_M_PCLK_CK,       // [165000000]
	kHDMI_PHY_TCLK_CK,      // [185625000]
	kAUDIO_DPLL_CK,			// [192000000]
	kLJCB_SERDESP_CK,		// [100000000]
	kLJCB_SERDESN_CK,		// [100000000]
	kPCIESS_50M_CK,			// [ 50000000]
	kPCIESS_125M_CK,		// [125000000]
	kSATASSP_CK,			// [100000000]
	kSATASSN_CK,			// [100000000]
	kSATASS_20M_CK,			// [ 20000000]
	kSATASS_50M_CK,			// [ 50000000]
	kSATASS_125M_CK,		// [125000000]
//--------------------------------------------------------------
	kDPLL_CLKOUT_COUNT
} DpllClkOut_e;

//------------------------------------------------------------------------------

typedef enum {
//    clock name                parent clock
//  ----------------------  ----------------------
	kDCAN0_FCK,			// kOSC0_CLKIN_CK	no prcm
	kDCAN1_FCK,			// kOSC0_CLKIN_CK	no prcm
	kSR0_FCK,			// kOSC0_CLKIN_CK	no prcm
	kSR1_FCK,			// kOSC0_CLKIN_CK	no prcm
	kSR2_FCK,			// kOSC0_CLKIN_CK	no prcm
	kSR3_FCK,			// kOSC0_CLKIN_CK	no prcm
	kARM_DPLL_CLKIN_CK, // sel-PLLSS_PREGS->ARM_CLKSRC[0]  kOSC0_CLKIN_CK/kRTC_DIVIDER_CK
	kMPU_CK,			// kARM_DPLL_CK  none
	kGEM_FCK,			// kDSP_DPLL_CK	 none
	kSYSCLK23_CK,		// kSGX_DPLL_CK; div-0x03B0[2:0] 1/2/3/4/5/6/7/8
	kSGX_CK,			// kSYSCLK23_CK  en-0x0920[1:0]
	kSGX_SYS_CK,		// kSYSCLK23_CK  none
	kSGX_MEM_CK,		// kSYSCLK23_CK  none
	kSYSCLK3_CK,		// kSYSCLK3_CK;  div-0x0308[2:0] 1/2/3/4/5/6/7/8
	kIVAHD0_CK,			// kSYSCLK3_CK;  en-0x0620[1:0]
	kL3_DPLL_CLKIN_CK,	// sel-PLLSS_PREGS->OSC_SRC[0]; kOSC0_CLKIN_CK/kOSC1_CLKIN_CK
	kSYSCLK4_CK,		// kL3_DPLL_CK;  none
	kL3_FAST_ICK,		// kSYSCLK4_CK;  en-0x15E4[1:0]
	kIVAHD0_ICK,		// kSYSCLK4_CK;  none
	kEXP_SLOT_ICK,		// kSYSCLK4_CK;  none
	kMMU_ICK,			// kSYSCLK4_CK;  en-0x159C[1:0]
	kGEM_ICK,			// kSYSCLK4_CK;  en-0x0420[1:0]
	kTPTC0_ICK,			// kSYSCLK4_CK;  en-0x15F8[1:0]
	kTPTC1_ICK,			// kSYSCLK4_CK;  en-0x15FC[1:0]
	kTPTC2_ICK,			// kSYSCLK4_CK;  en-0x1600[1:0]
	kTPTC3_ICK,			// kSYSCLK4_CK;  en-0x1604[1:0]
	kIVAHD0_SL2_ICK,	// kSYSCLK4_CK;  en-0x0624[1:0]
	kTPCC_ICK,			// kSYSCLK4_CK;  en-0x15F4[1:0]
	kFDIF_ICK,			// kSYSCLK4_CK;  none
	kHDVPSS_L3_ICK,		// kSYSCLK4_CK;  none
	kSYSCLK5_CK,		// kSYSCLK4_CK;  none
	kL3_MED_ICK,		// kSYSCLK5_CK;  en-0x15E4[1:0]
	kL4_FAST_ICK,		// kSYSCLK5_CK;  en-0x15E8[1:0]
	kSECURESS_ICK,		// kSYSCLK5_CK;  en-0x15C8[1:0]
	kTPGSW_ICK,			// kSYSCLK5_CK;  none
	kSATA_ICK,			// kSYSCLK5_CK;  en-0x0560[1:0]
	kPCIE_ICK,			// kSYSCLK5_CK;  en-0x0510[1:0]
	kVCP2_FCK,			// kSYSCLK5_CK;  en-0x15B8[1:0]
	kMLB_ICK,			// kSYSCLK5_CK;  en-0x1574[1:0]
	kFDIF_FCK,			// kSYSCLK5_CK;  none
	kDAP_ICK,			// kSYSCLK5_CK;  none
	kOCMC_RAM_ICK,		// kSYSCLK5_CK;  none
	kMMCHS2_ICK,		// kSYSCLK5_CK;  none
	kCPSW_ICK,			// kSYSCLK5_CK;  en-0x1404[1:0]
	kGEM_TRC_FCK,		// kSYSCLK5_CK;  none
	kMCASP3_ICK,		// kSYSCLK5_CK;  none
	kMCASP4_ICK,		// kSYSCLK5_CK;  none
	kMCASP5_ICK,		// kSYSCLK5_CK;  none
	kHDVPSS_L4_ICK,		// kSYSCLK5_CK;  none
	kSYSCLK6_CK,		// kSYSCLK4_CK;	 div-0x0314[0] 2/4 read only set to 2 
	kL3_SLOW_ICK,		// kSYSCLK6_CK;  en-0x15E4[1:0]
	kL4_SLOW_ICK,		// kSYSCLK6_CK;  en-0x15EC[1:0]
	kUART0_ICK,			// kSYSCLK6_CK;  none
	kUART1_ICK,			// kSYSCLK6_CK;  none
	kUART2_ICK,			// kSYSCLK6_CK;  none
	kUART3_ICK,			// kSYSCLK6_CK;  none
	kUART4_ICK,			// kSYSCLK6_CK;  none
	kUART5_ICK,			// kSYSCLK6_CK;  none
	kI2C0_ICK,			// kSYSCLK6_CK;  none
	kI2C1_ICK,			// kSYSCLK6_CK;  none
	kI2C2_ICK,			// kSYSCLK6_CK;  none
	kI2C3_ICK,			// kSYSCLK6_CK;  none
	kMCSPI0_ICK,		// kSYSCLK6_CK;  none
	kMCSPI1_ICK,		// kSYSCLK6_CK;  none
	kMCSPI2_ICK,		// kSYSCLK6_CK;  none
	kMCSPI3_ICK,		// kSYSCLK6_CK;  none
	kSDIO_ICK,			// kSYSCLK6_CK;  none
	kGPT1_ICK,			// kSYSCLK6_CK;  none
	kGPT2_ICK,			// kSYSCLK6_CK;  none
	kGPT3_ICK,			// kSYSCLK6_CK;  none
	kGPT4_ICK,			// kSYSCLK6_CK;  none
	kGPT5_ICK,			// kSYSCLK6_CK;  none
	kGPT6_ICK,			// kSYSCLK6_CK;  none
	kGPT7_ICK,			// kSYSCLK6_CK;  none
	kGPT8_ICK,			// kSYSCLK6_CK;  none
	kGPIO0_ICK,			// kSYSCLK6_CK;  en-0x155C[1:0]
	kGPIO1_ICK,			// kSYSCLK6_CK;  en-0x1560[1:0]
	kPRCM_ICK,			// kSYSCLK6_CK;  none
	kSMARTCARD0_ICK,	// kSYSCLK6_CK;  en-0x15BC[1:0]
	kSMARTCARD1_ICK,	// kSYSCLK6_CK;  en-0x15C0[1:0]
	kMCASP0_ICK,		// kSYSCLK6_CK;  none
	kMCASP1_ICK,		// kSYSCLK6_CK;  none
	kMCASP2_ICK,		// kSYSCLK6_CK;  none
	kMCBSP_ICK,			// kSYSCLK6_CK;  none
	kGPMC_FCK,			// kSYSCLK6_CK;  en-0x15D0[1:0]
	kHDMI_ICK,			// kSYSCLK6_CK;  none
	kMLBP_ICK,			// kSYSCLK6_CK;  en-0x1574[1:0]
	kWDT0_ICK,			// kSYSCLK6_CK;  en-0x158C[1:0]
	kWDT1_ICK,			// kSYSCLK6_CK;  none
	kSYNC_TIMER_ICK,	// kSYSCLK6_CK;  none
	kPATA_ICK,			// kSYSCLK6_CK;  en-0x1578[1:0]
	kMAILBOX_ICK,		// kSYSCLK6_CK;  en-0x1594[1:0]
	kSPINBOX_ICK,		// kSYSCLK6_CK;  en-0x1598[1:0]
	kSR0_ICK,			// kSYSCLK6_CK;  en-0x1608[1:0]
	kSR1_ICK,			// kSYSCLK6_CK;  en-0x160C[1:0]
	kSR2_ICK,			// kSYSCLK6_CK;  en-0x1610[1:0]
	kSR3_ICK,			// kSYSCLK6_CK;  en-0x1614[1:0]
	kUSB_ICK,			// kSYSCLK6_CK;  en-0x0558[1:0]
	kMMU_CFG_ICK,		// kSYSCLK6_CK;  en-0x15A8[1:0]
	kP1500_ICK,			// kSYSCLK6_CK;  none
	kELM_ICK,			// kSYSCLK6_CK;  none
	kMMCHS0_ICK,		// kSYSCLK6_CK;  none
	kMMCHS1_ICK,		// kSYSCLK6_CK;  none
	kATL_ICK,			// kSYSCLK6_CK;  none
	kFDIF_ENB_CK,		// kSYSCLK6_CK;  en-0x0724[1:0]
	kRTC_C32K_ICK,		// kSYSCLK6_CK;  none
	kDCAN0_ICK,			// kSYSCLK6_CK;  none
	kDCAN1_ICK,			// kSYSCLK6_CK;  none
	kISS_ICK,			// kISS_DPLL_CK; none
	kTPPSS_TSO_ICK,		// kISS_DPLL_CK; none
	kISS_DPLL_D2_CK,	// kISS_DPLL_CK; fixed div=2
	kDUCATI_ICK,		// kISS_DPLL_D2_CK;	en-0x0574[1:0]
	kHDVPSS_PROC_FCK,	// kHDVPSS_DPLL_CK none
	kHDVPSS_PROC_D2_FCK,// kHDVPSS_DPLL_CK; fixed div=2
	kUSB_DPLL_CLKIN_CK,	// kOSC0_CLKIN_CK	none
	kUSB_PHY0_RCLK_ICK,	// kUSB_DPLL_CK	none
	kUSB_PHY1_RCLK_ICK,	// kUSB_DPLL_CK	none
	kUSB_DPLL_DIV5_CK,	// kUSB_DPLL_CK;  fixed div=5
	kSYSCLK10_CK,		// kUSB_DPLL_DIV5_CK; DIV-0x0324[2:0] 1/2/3/4/5/6/7/8
	kMCSPI0_FCK,		// kSYSCLK10_CK; en-0x1590[1:0]
	kMCSPI1_FCK,		// kSYSCLK10_CK; en-0x1590[1:0]
	kMCSPI2_FCK,		// kSYSCLK10_CK; en-0x1590[1:0]
	kMCSPI3_FCK,		// kSYSCLK10_CK; en-0x1590[1:0]
	kI2C02_CK,			// kSYSCLK10_CK; en-0x1564[1:0]
	kI2C13_CK,			// kSYSCLK10_CK; en-0x1568[1:0]
	kI2C0_FCK,			// kI2C02_CK	none
	kI2C1_FCK,			// kI2C13_CK	none
	kI2C2_FCK,			// kI2C02_CK	none
	kI2C3_FCK,			// kI2C13_CK	none
	kUART0_FCK,			// kSYSCLK10_CK; en-1550[1:0] 
	kUART1_FCK,			// kSYSCLK10_CK; en-1554[1:0] 
	kUART2_FCK,			// kSYSCLK10_CK; en-1558[1:0] 
	kHDMI_CEC_DCC_FCK,	// kSYSCLK10_CK	none
	kSYSCLK8_CK,		// kUSB_DPLL_DIV5_CK none
	kMMCHS0_FCK,		// kSYSCLK8_CK;  en-0x161C[1:0]
	kMMCHS1_FCK,		// kSYSCLK8_CK;  en-0x1620[1:0]
	kMMCHS2_FCK,		// kSYSCLK8_CK;  en-0x1624[1:0]

	// kSYSCLK8_CK/kSYSCLK10_CK/kSYSCLK6_CK
	kUART3_FCK,			// en-0x1580[1:0]; sel-PLLSS_PREGS->McBSP_UART_CLKSRC[4:3] 
	kUART4_FCK,			// en-0x1584[1:0]; sel-PLLSS_PREGS->McBSP_UART_CLKSRC[6:5] 
	kUART5_FCK,			// en-0x1588[1:0]; sel-PLLSS_PREGS->McBSP_UART_CLKSRC[8:7] 
	kSECURESS_FCK,		// en-0x15C8[1:0]; sel-PLLSS_PREGS->SECSS_CLK_SRC[0] kISS_DPLL_D2_CK/kUSB_DPLL_DIV5_CK
	kTPPSS_FCK,			// kSECURESS_FCK; none
	kCSI2_PHY_FCK,		// kUSB_DPLL_DIV5_CK; fixed div=2
	kDDR_DPLL_CLKIN_CK,	// kOSC0_CLKIN_CK; none
	kDDR0_PHY_FCK,		// kDDR_DPLL_CK;  en-PLLSS_PREGS->EMIF_CLK_GATE[0] fixed div=1
	kDDR1_PHY_FCK,		// kDDR_DPLL_CK;  en-PLLSS_PREGS->EMIF_CLK_GATE[1] fixed div=1
	kDDR0_HALF_FCK,		// kDDR_DPLL_CK;  en-PLLSS_PREGS->EMIF_CLK_GATE[0] fixed div=2
	kDDR1_HALF_FCK,		// kDDR_DPLL_CK;  en-PLLSS_PREGS->EMIF_CLK_GATE[1] fixed div=2
	kDDR0_PHY_D2_FCK,	// kDDR0_HALF_FCK none
	kDDR0_EMIF_FCK,		// kDDR0_HALF_FCK none
	kDMM_PHY_FCK,		// kDDR0_HALF_FCK none
	kDDR1_PHY_D2_FCK,	// kDDR1_HALF_FCK none
	kDDR1_EMIF_FCK,		// kDDR1_HALF_FCK none
	kVIDEO0_DPLL_CLKIN_CK,// sel-PLLSS_PREGS->OSC_SRC[16]; kOSC0_CLKIN_CK/kOSC1_CLKIN_CK
	kVIDEO1_DPLL_CLKIN_CK,// sel-PLLSS_PREGS->OSC_SRC[17]; kOSC0_CLKIN_CK/kOSC1_CLKIN_CK
	kHDMI_DPLL_CLKIN_CK,  // sel-PLLSS_PREGS->OSC_SRC[18]; kOSC0_CLKIN_CK/kOSC1_CLKIN_CK
	kHDMI_DPLL_MUXOUT_CK,// sel-PLLSS_PREGS->VIDEO_PLL_CLKSRC[0] kHDMI_DPLL_CK/kVIDEO_M_PCLK_CK
	kVIDEO012_DPLL_MUXOUT_CK,// sel-PLLSS_PREGS->VIDEO_PLL_CLKSRC[9:8] kVIDEO0_DPLL_CK/kHDMI_DPLL_MUXOUT_CK/kVIDEO1_DPLL_CK
	kSYSCLK16_D1MUX_CK, // kVIDEO0_DPLL_CK; div-0x348[2:0] 1/2/3/4/5/6/7/8
	kSYSCLK16_B3MUX_CK,	// kHDMI_DPLL_MUXOUT_CK; div-0x0340[1:0] 1/2/22
	kSYSCLK14_C1MUX_CK,	// kVIDEO1_DPLL_CK; div-0x0344[1:0] 1/2/22
	kSYSCLK16_CK,		// sel-0x0374[0]   kSYSCLK16_D1MUX_CK/kSYSCLK16_B3MUX_CK
	kTPPSS_STC1_FCK,	// kSYSCLK16_CK;    none 
	kHD_VENC_G_CK,		// sel-PLLSS_PREGS->VIDEO_PLL_CLKSRC[24] kVIDEO1_DPLL_CK/kHDMI_DPLL_MUXOUT_CK
	kHD_VENC_D_CK,		// kHDMI_DPLL_MUXOUT_CK none
	kHDMI_PHY_GCLK_CK,	// kHD_VENC_D_CK   none
	kSD_VENC_CK,		// kVIDEO0_DPLL_CK none
	kSYSCLK14_CK,		// sel-0x370[1:0] kSYSCLK16_B3MUX_CK/kVIDEO0_DPLL_CLKIN_CK/kSYSCLK14_C1MUX_CK/
	kTPPSS_STC0_FCK,	// sel-PLLSS_PREGS->VIDEO_PLL_CLKSRC[17..16] kSYSCLK14_CK/kXREF0_CK/kXREF1_CK/kXREF2_CK
	kAUDIO_DPLL_CLK2_CK,// sel-PLLSS_PREGS->VIDEO_PLL_CLKSRC[19..18] kISS_DPLL_D2_CK/kISS_DPLL_CK/kTSI0_DCK_CK/kTSI1_DCK_CK
	kAUDIO_DPLL_CLKIN_CK,// sel-PLLSS_PREGS->OSC_SRC[24];  kOSC0_CLKIN_CK/kOSC1_CLKIN_CK
	kAUDIO_DPLL_CLK1_CK,// kRTC_DIVIDER_CK;  div-0x35C[2..0] 1/2/3/4/5/6/7/8
	kAUDIO_PRCM_CLKIN_CK,// sel-PLLSS_PREGS->SYSCLK_18_SRC[0] kRTC_DIVIDER_CK/kSYS_32K_CLKIN_CK
	kSYSCLK18_CK,		// sel-0x0378[0] kAUDIO_PRCM_CLKIN_CK/kAUDIO_DPLL_CLK1_CK 
	kRTC_C32K_FCK,		// kSYSCLK18_CK none
	kSYSCLK19_CK,		// kAUDIO_DPLL_CLK2_CK;      div-0x34C[2..0] 1/2/3/4/5/6/7/8
	kSYSCLK20_CK,		// kAUDIO_DPLL_CK;           div-0x350[2..0] 1/2/3/4/5/6/7/8
	kSYSCLK21_CK,		// kVIDEO012_DPLL_MUXOUT_CK; div-0x354[2..0] 1/2/3/4/5/6/7/8
	kSYSCLK22_CK,		// kOSC0_CLKIN_CK none
	kAUDIO_PRCM1_OUT_CK,// en-0x154C[1..0]; sel-0x388[1..0] kSYSCLK20_CK/kSYSCLK21_CK/kSYSCLK22_CK
	kMCBSP_FCK,			// sel - PLLSS_PREGS->McBSP_UART_CLKSRC[2..0] kAUDIO_PRCM1_OUT_CK/kXREF0_CK/kXREF1_CK/kXREF2_CK/kOSC1_X1_CK

//kSYSCLK20_CK/kSYSCLK21_CK/kSYSCLK22_CK
	kMCASP0_FCK,		// en-0x1540[1..0]; sel-0x37C[1..0]
	kMCASP1_FCK,		// en-0x1544[1..0]; sel-0x380[1..0]
	kMCASP2_FCK,		// en-0x1548[1..0]; sel-0x384[1..0]
	kHDMI_I2S_CK,		// en-0x0824[1..0]; sel-0x3AC[1..0] 

	// kHDMI_I2S_CK/kXREF0_CK/kXREF1_CK/kXREF2_CK/kOSC1_X1_CK
	kHDMI_I2S_FCK,		// sel-PLLSS_PREGS->HDMI_I2S_CLKSRC[2..0]
	kTPPSS_TSO_FCK,		// kSYSCLK19_CK en-0x554[1..0]
	kATL_FCK,			// sel-PLLSS_PREGS->MLB_ATL_CLKSRC[17..16] kSYSCLK19_CK/kAUDIO_DPLL_CK/kVIDEO012_DPLL_MUXOUT_CK
	kGPIO0_DBCK,		// kSYSCLK18_CK none
	kGPIO1_DBCK,		// kSYSCLK18_CK none
	kRTC_FCK,			// kSYSCLK18_CK none
	kMMCHS0_DBCK,		// kSYSCLK18_CK none
	kMMCHS1_DBCK,		// kSYSCLK18_CK none
	kMMCHS2_DBCK,		// kSYSCLK18_CK none
	kSYNC_TIMER_FCK,	// kSYSCLK18_CK none
	kBANDGAPS_FCK,		// kSYSCLK18_CK none
	kARM_OPER_FCK,		// kSYSCLK18_CK none

	//kSYSCLK18_CK/kXREF0_CK/kXREF1_CK/kXREF2_CK/kOSC0_CLKIN_CK/kOSC1_X1_CK/kTCLKIN_CK
	kGPT1_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[5..3]
	kGPT2_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[8..6]
	kGPT3_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[11..9]
	kGPT4_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[18..16]
	kGPT5_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[21..19]
	kGPT6_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[24..22]
	kGPT7_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[27..25]
	kGPT8_FCK,			// sel-PLLSS_PREGS->TIMER_CLK_CHANGE[2..0]
	kMCASP_AUXCLK_MUX0_CK, // sel-PLLSS_PREGS->MLB_ATL_CLKSRC[0] kMLB_ICK/kMLBP_ICK

	//kMCASP_AUXCLK_MUX0_CK/kAUDIO_DPLL_CK/kVIDEO012_DPLL_MUXOUT_CK/kXREF0_CK/kXREF1_CK/kXREF2_CK/kOSC1_X1_CK
	kMCASP3_FCK,		// sel-PLLSS_PREGS->McASP345_AUX_CLKSRC[2..0]
	kMCASP4_FCK,		// sel-PLLSS_PREGS->McASP345_AUX_CLKSRC[10..8]
	kMCASP5_FCK,		// sel-PLLSS_PREGS->McASP345_AUX_CLKSRC[18..16]
	
	//kXREF0_CK/kXREF1_CK/kXREF2_CK/kOSC1_X1_CK/kATL0_CLK_CK/kATL1_CLK_CK/kATL2_CLK_CK/kATL3_CLK_CK
	kMCASP0_AHX_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[2..0]
	kMCASP0_AHR_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[5..3]
	kMCASP1_AHX_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[8..6]
	kMCASP1_AHR_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[11..9]
	kMCASP2_AHX_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[18..16]
	kMCASP3_AHX_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[21..19]
	kMCASP4_AHX_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[24..22]
	kMCASP5_AHX_CK,		// sel-PLLSS_PREGS->McASP_AHCLK_CLKSRC[27..25]
	kCPTS_RFT_CLK_CK,	// kVIDEO0_DPLL_CK/kVIDEO1_DPLL_CK/kAUDIO_DPLL_CK/kHDMI_DPLL_MUXOUT_CK/kL3_DPLL_CK
						// sel-PLLSS_PREGS->RMII_REFCLK_SRC[3..1]
	kPCIESS_20M_CK,		// kOSC0_CLKIN_CK     none
	kPCIESSP_CK,		// kLJCB_SERDESP_CK   none
	kPCIESSN_CK,		// kLJCB_SERDESN_CK   none
	kEMAC_RMII_FCK,		// kSATASS_50M_CK/kEXTERNAL_CK sel-PLLSS_PREGS->RMII_REFCLK_SRC[0] 
	kEMAC_GMII_FCK,		// kSATASS_125M_CK		 none
	kWDT0_FCK,			// kRTC_DIVIDER_CK/kRCOSC_32K_CK; sel PLLSS_PREGS->WDT0_SRC[0] 
	kWDT1_FCK,			// kRCOSC_32K_CK -  none
	kCLKOUT_PRCM_MUX_CK,// kDSP_DPLL_CK/kHDVICP_DPLL_CK/kVIDEO0_DPLL_CK/kRTC_DIVIDER_CK sel-0x100[1..0]
	kCLKOUT_PRCM_CK,	// kCLKOUT_PRCM_MUX_CK    en-0x0100[7]; div-0x100[5..3] 1,2,4,8,16

	// kCLKOUT_PRCM_CK/kSATASS_125M_CK/kPCIESS_125M_CK/kHDVPSS_PROC_D2_FCK/kISS_DPLL_D2_CK/
	// kL3_DPLL_CK/kOSC0_CLKIN_CK/kOSC1_CLKIN_CK//kMPU_CK/kSGX_DPLL_CK/kRCOSC_32K_CK
	kSYS_CLKOUT0,		// PLLSS_PREGS->CLKOUT_MUX[3..0]   - clkout0
	kSYS_CLKOUT1,		// PLLSS_PREGS->CLKOUT_MUX[19..16] - clkout1
// end of clock definitions
    kSOURCE_CLOCK_COUNT,       
} SourceClock_e;

#define NOCLOCK  9999

//------------------------------------------------------------------------------

#ifdef __cplusplus
}
#endif

#endif
